USE `aoxiaoyou`;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS content_assets (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `asset_kind` VARCHAR(32) NOT NULL COMMENT 'image/icon/map_tile/audio/json/other',
  `bucket_name` VARCHAR(128) NOT NULL DEFAULT '',
  `region` VARCHAR(64) NOT NULL DEFAULT '',
  `object_key` VARCHAR(512) NOT NULL DEFAULT '',
  `canonical_url` VARCHAR(1024) NOT NULL DEFAULT '',
  `mime_type` VARCHAR(128) NOT NULL DEFAULT '',
  `locale_code` VARCHAR(16) NOT NULL DEFAULT '',
  `original_filename` VARCHAR(255) NOT NULL DEFAULT '',
  `file_extension` VARCHAR(32) NOT NULL DEFAULT '',
  `upload_source` VARCHAR(32) NOT NULL DEFAULT 'picker',
  `client_relative_path` VARCHAR(1024) NULL,
  `uploaded_by_admin_id` BIGINT NULL,
  `uploaded_by_admin_name` VARCHAR(128) NOT NULL DEFAULT '',
  `file_size_bytes` BIGINT NOT NULL DEFAULT 0,
  `width_px` INT NULL,
  `height_px` INT NULL,
  `checksum` VARCHAR(128) NOT NULL DEFAULT '',
  `etag` VARCHAR(128) NOT NULL DEFAULT '',
  `processing_policy_code` VARCHAR(64) NOT NULL DEFAULT 'passthrough',
  `processing_profile_json` JSON NULL,
  `processing_status` VARCHAR(32) NOT NULL DEFAULT 'stored',
  `processing_note` TEXT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'draft',
  `published_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  KEY `idx_content_assets_kind_status` (`asset_kind`, `status`),
  KEY `idx_content_assets_locale` (`locale_code`),
  KEY `idx_content_assets_upload_source` (`upload_source`),
  KEY `idx_content_assets_processing_policy` (`processing_policy_code`),
  KEY `idx_content_assets_uploaded_by_admin_id` (`uploaded_by_admin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS app_runtime_settings (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `setting_group` VARCHAR(64) NOT NULL,
  `setting_key` VARCHAR(128) NOT NULL,
  `locale_code` VARCHAR(16) NOT NULL DEFAULT '',
  `title_zh` VARCHAR(255) NOT NULL DEFAULT '',
  `title_en` VARCHAR(255) NOT NULL DEFAULT '',
  `title_zht` VARCHAR(255) NOT NULL DEFAULT '',
  `title_pt` VARCHAR(255) NOT NULL DEFAULT '',
  `value_json` JSON NULL,
  `value_text` LONGTEXT NULL,
  `description_zh` TEXT NULL,
  `description_en` TEXT NULL,
  `description_zht` TEXT NULL,
  `description_pt` TEXT NULL,
  `asset_id` BIGINT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'draft',
  `sort_order` INT NOT NULL DEFAULT 0,
  `published_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY `uk_runtime_settings_group_key_locale` (`setting_group`, `setting_key`, `locale_code`),
  KEY `idx_runtime_settings_status_sort` (`status`, `sort_order`),
  KEY `idx_runtime_settings_group` (`setting_group`),
  KEY `idx_runtime_settings_asset_id` (`asset_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cities (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `code` VARCHAR(64) NOT NULL,
  `name_zh` VARCHAR(128) NOT NULL,
  `name_en` VARCHAR(128) NOT NULL DEFAULT '',
  `name_zht` VARCHAR(128) NOT NULL DEFAULT '',
  `name_pt` VARCHAR(128) NOT NULL DEFAULT '',
  `subtitle_zh` VARCHAR(255) NOT NULL DEFAULT '',
  `subtitle_en` VARCHAR(255) NOT NULL DEFAULT '',
  `subtitle_zht` VARCHAR(255) NOT NULL DEFAULT '',
  `subtitle_pt` VARCHAR(255) NOT NULL DEFAULT '',
  `country_code` VARCHAR(16) NOT NULL DEFAULT '',
  `source_coordinate_system` VARCHAR(32) NOT NULL DEFAULT 'GCJ02',
  `source_center_lat` DECIMAL(10,7) NULL,
  `source_center_lng` DECIMAL(10,7) NULL,
  `center_lat` DECIMAL(10,7) NULL,
  `center_lng` DECIMAL(10,7) NULL,
  `default_zoom` INT NOT NULL DEFAULT 13,
  `unlock_type` VARCHAR(32) NOT NULL DEFAULT 'default',
  `unlock_condition_json` JSON NULL,
  `cover_asset_id` BIGINT NULL,
  `banner_asset_id` BIGINT NULL,
  `description_zh` TEXT NULL,
  `description_en` TEXT NULL,
  `description_zht` TEXT NULL,
  `description_pt` TEXT NULL,
  `popup_config_json` JSON NULL,
  `display_config_json` JSON NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'draft',
  `sort_order` INT NOT NULL DEFAULT 0,
  `published_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY `uk_cities_code` (`code`),
  KEY `idx_cities_status_sort` (`status`, `sort_order`),
  KEY `idx_cities_cover_asset_id` (`cover_asset_id`),
  KEY `idx_cities_banner_asset_id` (`banner_asset_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sub_maps (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `city_id` BIGINT NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  `name_zh` VARCHAR(128) NOT NULL,
  `name_en` VARCHAR(128) NOT NULL DEFAULT '',
  `name_zht` VARCHAR(128) NOT NULL DEFAULT '',
  `name_pt` VARCHAR(128) NOT NULL DEFAULT '',
  `subtitle_zh` VARCHAR(255) NOT NULL DEFAULT '',
  `subtitle_en` VARCHAR(255) NOT NULL DEFAULT '',
  `subtitle_zht` VARCHAR(255) NOT NULL DEFAULT '',
  `subtitle_pt` VARCHAR(255) NOT NULL DEFAULT '',
  `description_zh` TEXT NULL,
  `description_en` TEXT NULL,
  `description_zht` TEXT NULL,
  `description_pt` TEXT NULL,
  `cover_asset_id` BIGINT NULL,
  `source_coordinate_system` VARCHAR(32) NOT NULL DEFAULT 'GCJ02',
  `source_center_lat` DECIMAL(10,7) NULL,
  `source_center_lng` DECIMAL(10,7) NULL,
  `center_lat` DECIMAL(10,7) NULL,
  `center_lng` DECIMAL(10,7) NULL,
  `bounds_json` JSON NULL,
  `popup_config_json` JSON NULL,
  `display_config_json` JSON NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(16) NOT NULL DEFAULT 'draft',
  `published_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY `uk_sub_maps_code` (`code`),
  KEY `idx_sub_maps_city_status_sort` (`city_id`, `status`, `sort_order`),
  KEY `idx_sub_maps_cover_asset_id` (`cover_asset_id`),
  CONSTRAINT `fk_sub_maps_city` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS storylines (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `city_id` BIGINT NULL,
  `code` VARCHAR(64) NOT NULL,
  `name_zh` VARCHAR(128) NOT NULL,
  `name_en` VARCHAR(128) NOT NULL DEFAULT '',
  `name_zht` VARCHAR(128) NOT NULL DEFAULT '',
  `name_pt` VARCHAR(128) NOT NULL DEFAULT '',
  `description_zh` TEXT NULL,
  `description_en` TEXT NULL,
  `description_zht` TEXT NULL,
  `description_pt` TEXT NULL,
  `estimated_minutes` INT NOT NULL DEFAULT 0,
  `difficulty` VARCHAR(32) NOT NULL DEFAULT 'easy',
  `cover_asset_id` BIGINT NULL,
  `banner_asset_id` BIGINT NULL,
  `reward_badge_zh` VARCHAR(128) NOT NULL DEFAULT '',
  `reward_badge_en` VARCHAR(128) NOT NULL DEFAULT '',
  `reward_badge_zht` VARCHAR(128) NOT NULL DEFAULT '',
  `reward_badge_pt` VARCHAR(128) NOT NULL DEFAULT '',
  `status` VARCHAR(16) NOT NULL DEFAULT 'draft',
  `sort_order` INT NOT NULL DEFAULT 0,
  `published_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY `uk_storylines_code` (`code`),
  KEY `idx_storylines_status_sort` (`status`, `sort_order`),
  KEY `idx_storylines_city_id` (`city_id`),
  KEY `idx_storylines_cover_asset_id` (`cover_asset_id`),
  CONSTRAINT `fk_storylines_city` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pois (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `city_id` BIGINT NOT NULL,
  `sub_map_id` BIGINT NULL,
  `storyline_id` BIGINT NULL,
  `code` VARCHAR(64) NOT NULL DEFAULT '',
  `name_zh` VARCHAR(128) NOT NULL,
  `name_en` VARCHAR(128) NOT NULL DEFAULT '',
  `name_zht` VARCHAR(128) NOT NULL DEFAULT '',
  `name_pt` VARCHAR(128) NOT NULL DEFAULT '',
  `subtitle_zh` VARCHAR(255) NOT NULL DEFAULT '',
  `subtitle_en` VARCHAR(255) NOT NULL DEFAULT '',
  `subtitle_zht` VARCHAR(255) NOT NULL DEFAULT '',
  `subtitle_pt` VARCHAR(255) NOT NULL DEFAULT '',
  `address_zh` VARCHAR(255) NOT NULL DEFAULT '',
  `address_en` VARCHAR(255) NOT NULL DEFAULT '',
  `address_zht` VARCHAR(255) NOT NULL DEFAULT '',
  `address_pt` VARCHAR(255) NOT NULL DEFAULT '',
  `source_coordinate_system` VARCHAR(32) NOT NULL DEFAULT 'GCJ02',
  `source_latitude` DECIMAL(10,7) NULL,
  `source_longitude` DECIMAL(10,7) NULL,
  `latitude` DECIMAL(10,7) NULL,
  `longitude` DECIMAL(10,7) NULL,
  `trigger_radius` INT NOT NULL DEFAULT 50,
  `manual_checkin_radius` INT NOT NULL DEFAULT 200,
  `stay_seconds` INT NOT NULL DEFAULT 30,
  `category_code` VARCHAR(64) NOT NULL DEFAULT '',
  `difficulty` VARCHAR(32) NOT NULL DEFAULT 'easy',
  `district_zh` VARCHAR(128) NOT NULL DEFAULT '',
  `district_en` VARCHAR(128) NOT NULL DEFAULT '',
  `district_zht` VARCHAR(128) NOT NULL DEFAULT '',
  `district_pt` VARCHAR(128) NOT NULL DEFAULT '',
  `cover_asset_id` BIGINT NULL,
  `map_icon_asset_id` BIGINT NULL,
  `audio_asset_id` BIGINT NULL,
  `description_zh` TEXT NULL,
  `description_en` TEXT NULL,
  `description_zht` TEXT NULL,
  `description_pt` TEXT NULL,
  `intro_title_zh` VARCHAR(255) NOT NULL DEFAULT '',
  `intro_title_en` VARCHAR(255) NOT NULL DEFAULT '',
  `intro_title_zht` VARCHAR(255) NOT NULL DEFAULT '',
  `intro_title_pt` VARCHAR(255) NOT NULL DEFAULT '',
  `intro_summary_zh` TEXT NULL,
  `intro_summary_en` TEXT NULL,
  `intro_summary_zht` TEXT NULL,
  `intro_summary_pt` TEXT NULL,
  `popup_config_json` JSON NULL,
  `display_config_json` JSON NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'draft',
  `sort_order` INT NOT NULL DEFAULT 0,
  `published_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY `uk_pois_city_code` (`city_id`, `code`),
  KEY `idx_pois_status_sort` (`status`, `sort_order`),
  KEY `idx_pois_city_id` (`city_id`),
  KEY `idx_pois_sub_map_id` (`sub_map_id`),
  KEY `idx_pois_storyline_id` (`storyline_id`),
  KEY `idx_pois_cover_asset_id` (`cover_asset_id`),
  KEY `idx_pois_map_icon_asset_id` (`map_icon_asset_id`),
  CONSTRAINT `fk_pois_city` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`),
  CONSTRAINT `fk_pois_sub_map` FOREIGN KEY (`sub_map_id`) REFERENCES `sub_maps` (`id`),
  CONSTRAINT `fk_pois_storyline` FOREIGN KEY (`storyline_id`) REFERENCES `storylines` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS content_asset_links (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `entity_type` VARCHAR(32) NOT NULL,
  `entity_id` BIGINT NOT NULL,
  `usage_type` VARCHAR(32) NOT NULL,
  `asset_id` BIGINT NOT NULL,
  `title_zh` VARCHAR(255) NOT NULL DEFAULT '',
  `title_en` VARCHAR(255) NOT NULL DEFAULT '',
  `title_zht` VARCHAR(255) NOT NULL DEFAULT '',
  `title_pt` VARCHAR(255) NOT NULL DEFAULT '',
  `description_zh` TEXT NULL,
  `description_en` TEXT NULL,
  `description_zht` TEXT NULL,
  `description_pt` TEXT NULL,
  `display_config_json` JSON NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(16) NOT NULL DEFAULT 'draft',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  KEY `idx_content_asset_links_entity_status_sort` (`entity_type`, `entity_id`, `status`, `sort_order`),
  KEY `idx_content_asset_links_usage_type` (`usage_type`),
  KEY `idx_content_asset_links_asset_id` (`asset_id`),
  CONSTRAINT `fk_content_asset_links_asset` FOREIGN KEY (`asset_id`) REFERENCES `content_assets` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS story_chapters (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `storyline_id` BIGINT NOT NULL,
  `chapter_order` INT NOT NULL,
  `title_zh` VARCHAR(255) NOT NULL,
  `title_en` VARCHAR(255) NOT NULL DEFAULT '',
  `title_zht` VARCHAR(255) NOT NULL DEFAULT '',
  `title_pt` VARCHAR(255) NOT NULL DEFAULT '',
  `summary_zh` TEXT NULL,
  `summary_en` TEXT NULL,
  `summary_zht` TEXT NULL,
  `summary_pt` TEXT NULL,
  `detail_zh` LONGTEXT NULL,
  `detail_en` LONGTEXT NULL,
  `detail_zht` LONGTEXT NULL,
  `detail_pt` LONGTEXT NULL,
  `achievement_zh` VARCHAR(255) NOT NULL DEFAULT '',
  `achievement_en` VARCHAR(255) NOT NULL DEFAULT '',
  `achievement_zht` VARCHAR(255) NOT NULL DEFAULT '',
  `achievement_pt` VARCHAR(255) NOT NULL DEFAULT '',
  `collectible_zh` VARCHAR(255) NOT NULL DEFAULT '',
  `collectible_en` VARCHAR(255) NOT NULL DEFAULT '',
  `collectible_zht` VARCHAR(255) NOT NULL DEFAULT '',
  `collectible_pt` VARCHAR(255) NOT NULL DEFAULT '',
  `location_name_zh` VARCHAR(255) NOT NULL DEFAULT '',
  `location_name_en` VARCHAR(255) NOT NULL DEFAULT '',
  `location_name_zht` VARCHAR(255) NOT NULL DEFAULT '',
  `location_name_pt` VARCHAR(255) NOT NULL DEFAULT '',
  `media_asset_id` BIGINT NULL,
  `unlock_type` VARCHAR(32) NOT NULL DEFAULT 'sequence',
  `unlock_param_json` JSON NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'draft',
  `sort_order` INT NOT NULL DEFAULT 0,
  `published_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY `uk_story_chapters_storyline_order` (`storyline_id`, `chapter_order`),
  KEY `idx_story_chapters_status_sort` (`status`, `sort_order`),
  KEY `idx_story_chapters_storyline_id` (`storyline_id`),
  CONSTRAINT `fk_story_chapters_storyline` FOREIGN KEY (`storyline_id`) REFERENCES `storylines` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tip_articles (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `city_id` BIGINT NULL,
  `code` VARCHAR(64) NOT NULL DEFAULT '',
  `category_code` VARCHAR(64) NOT NULL DEFAULT '',
  `title_zh` VARCHAR(255) NOT NULL,
  `title_en` VARCHAR(255) NOT NULL DEFAULT '',
  `title_zht` VARCHAR(255) NOT NULL DEFAULT '',
  `title_pt` VARCHAR(255) NOT NULL DEFAULT '',
  `summary_zh` TEXT NULL,
  `summary_en` TEXT NULL,
  `summary_zht` TEXT NULL,
  `summary_pt` TEXT NULL,
  `content_zh` LONGTEXT NULL,
  `content_en` LONGTEXT NULL,
  `content_zht` LONGTEXT NULL,
  `content_pt` LONGTEXT NULL,
  `author_display_name` VARCHAR(128) NOT NULL DEFAULT '',
  `location_name_zh` VARCHAR(128) NOT NULL DEFAULT '',
  `location_name_en` VARCHAR(128) NOT NULL DEFAULT '',
  `location_name_zht` VARCHAR(128) NOT NULL DEFAULT '',
  `location_name_pt` VARCHAR(128) NOT NULL DEFAULT '',
  `tags_json` JSON NULL,
  `cover_asset_id` BIGINT NULL,
  `source_type` VARCHAR(32) NOT NULL DEFAULT 'editorial',
  `status` VARCHAR(16) NOT NULL DEFAULT 'draft',
  `sort_order` INT NOT NULL DEFAULT 0,
  `published_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  KEY `idx_tip_articles_status_sort` (`status`, `sort_order`),
  KEY `idx_tip_articles_city_id` (`city_id`),
  KEY `idx_tip_articles_cover_asset_id` (`cover_asset_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rewards (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `code` VARCHAR(64) NOT NULL,
  `name_zh` VARCHAR(128) NOT NULL,
  `name_en` VARCHAR(128) NOT NULL DEFAULT '',
  `name_zht` VARCHAR(128) NOT NULL DEFAULT '',
  `name_pt` VARCHAR(128) NOT NULL DEFAULT '',
  `subtitle_zh` VARCHAR(255) NOT NULL DEFAULT '',
  `subtitle_en` VARCHAR(255) NOT NULL DEFAULT '',
  `subtitle_zht` VARCHAR(255) NOT NULL DEFAULT '',
  `subtitle_pt` VARCHAR(255) NOT NULL DEFAULT '',
  `description_zh` TEXT NULL,
  `description_en` TEXT NULL,
  `description_zht` TEXT NULL,
  `description_pt` TEXT NULL,
  `highlight_zh` VARCHAR(255) NOT NULL DEFAULT '',
  `highlight_en` VARCHAR(255) NOT NULL DEFAULT '',
  `highlight_zht` VARCHAR(255) NOT NULL DEFAULT '',
  `highlight_pt` VARCHAR(255) NOT NULL DEFAULT '',
  `stamp_cost` INT NOT NULL DEFAULT 0,
  `inventory_total` INT NOT NULL DEFAULT 0,
  `inventory_redeemed` INT NOT NULL DEFAULT 0,
  `cover_asset_id` BIGINT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'draft',
  `sort_order` INT NOT NULL DEFAULT 0,
  `publish_start_at` DATETIME NULL,
  `publish_end_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY `uk_rewards_code` (`code`),
  KEY `idx_rewards_status_sort` (`status`, `sort_order`),
  KEY `idx_rewards_publish_window` (`publish_start_at`, `publish_end_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stamps (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `code` VARCHAR(64) NOT NULL,
  `name_zh` VARCHAR(128) NOT NULL,
  `name_en` VARCHAR(128) NOT NULL DEFAULT '',
  `name_zht` VARCHAR(128) NOT NULL DEFAULT '',
  `name_pt` VARCHAR(128) NOT NULL DEFAULT '',
  `description_zh` TEXT NULL,
  `description_en` TEXT NULL,
  `description_zht` TEXT NULL,
  `description_pt` TEXT NULL,
  `stamp_type` VARCHAR(32) NOT NULL DEFAULT 'location',
  `rarity` VARCHAR(32) NOT NULL DEFAULT 'common',
  `icon_asset_id` BIGINT NULL,
  `related_poi_id` BIGINT NULL,
  `related_storyline_id` BIGINT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'draft',
  `sort_order` INT NOT NULL DEFAULT 0,
  `published_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY `uk_stamps_code` (`code`),
  KEY `idx_stamps_status_sort` (`status`, `sort_order`),
  KEY `idx_stamps_related_poi_id` (`related_poi_id`),
  KEY `idx_stamps_related_storyline_id` (`related_storyline_id`),
  CONSTRAINT `fk_stamps_related_poi` FOREIGN KEY (`related_poi_id`) REFERENCES `pois` (`id`),
  CONSTRAINT `fk_stamps_related_storyline` FOREIGN KEY (`related_storyline_id`) REFERENCES `storylines` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notifications (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `code` VARCHAR(64) NOT NULL,
  `title_zh` VARCHAR(255) NOT NULL,
  `title_en` VARCHAR(255) NOT NULL DEFAULT '',
  `title_zht` VARCHAR(255) NOT NULL DEFAULT '',
  `title_pt` VARCHAR(255) NOT NULL DEFAULT '',
  `content_zh` TEXT NULL,
  `content_en` TEXT NULL,
  `content_zht` TEXT NULL,
  `content_pt` TEXT NULL,
  `notification_type` VARCHAR(32) NOT NULL DEFAULT 'system',
  `target_scope` VARCHAR(64) NOT NULL DEFAULT 'all',
  `cover_asset_id` BIGINT NULL,
  `action_url` VARCHAR(1024) NOT NULL DEFAULT '',
  `status` VARCHAR(16) NOT NULL DEFAULT 'draft',
  `sort_order` INT NOT NULL DEFAULT 0,
  `publish_start_at` DATETIME NULL,
  `publish_end_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY `uk_notifications_code` (`code`),
  KEY `idx_notifications_status_sort` (`status`, `sort_order`),
  KEY `idx_notifications_publish_window` (`publish_start_at`, `publish_end_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_profiles (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `open_id` VARCHAR(64) NOT NULL,
  `nickname` VARCHAR(128) NOT NULL DEFAULT '',
  `avatar_url` VARCHAR(1024) NOT NULL DEFAULT '',
  `level` INT NOT NULL DEFAULT 1,
  `title_zh` VARCHAR(128) NOT NULL DEFAULT '',
  `title_en` VARCHAR(128) NOT NULL DEFAULT '',
  `title_zht` VARCHAR(128) NOT NULL DEFAULT '',
  `title_pt` VARCHAR(128) NOT NULL DEFAULT '',
  `total_stamps` INT NOT NULL DEFAULT 0,
  `current_exp` INT NOT NULL DEFAULT 0,
  `next_level_exp` INT NOT NULL DEFAULT 100,
  `current_city_id` BIGINT NULL,
  `current_locale_code` VARCHAR(16) NOT NULL DEFAULT 'zh-Hans',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY `uk_user_profiles_open_id` (`open_id`),
  KEY `idx_user_profiles_city_id` (`current_city_id`),
  CONSTRAINT `fk_user_profiles_city` FOREIGN KEY (`current_city_id`) REFERENCES `cities` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_progress (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `storyline_id` BIGINT NULL,
  `active_storyline_id` BIGINT NULL,
  `completed_storyline` TINYINT NOT NULL DEFAULT 0,
  `completed_chapter_ids_json` JSON NULL,
  `collected_stamp_ids_json` JSON NULL,
  `progress_percent` INT NOT NULL DEFAULT 0,
  `last_seen_at` DATETIME NULL,
  `completed_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY `uk_user_progress_user_storyline` (`user_id`, `storyline_id`),
  KEY `idx_user_progress_user_id` (`user_id`),
  KEY `idx_user_progress_storyline_id` (`storyline_id`),
  CONSTRAINT `fk_user_progress_user` FOREIGN KEY (`user_id`) REFERENCES `user_profiles` (`id`),
  CONSTRAINT `fk_user_progress_storyline` FOREIGN KEY (`storyline_id`) REFERENCES `storylines` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_checkins (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `poi_id` BIGINT NOT NULL,
  `trigger_mode` VARCHAR(16) NOT NULL DEFAULT 'gps',
  `distance_meters` DECIMAL(10,2) NULL,
  `gps_accuracy` DECIMAL(10,2) NULL,
  `latitude` DECIMAL(10,7) NULL,
  `longitude` DECIMAL(10,7) NULL,
  `checked_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY `idx_user_checkins_user_id` (`user_id`),
  KEY `idx_user_checkins_poi_id` (`poi_id`),
  KEY `idx_user_checkins_checked_at` (`checked_at`),
  CONSTRAINT `fk_user_checkins_user` FOREIGN KEY (`user_id`) REFERENCES `user_profiles` (`id`),
  CONSTRAINT `fk_user_checkins_poi` FOREIGN KEY (`poi_id`) REFERENCES `pois` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_preferences (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `interface_mode` VARCHAR(32) NOT NULL DEFAULT 'standard',
  `font_scale` DECIMAL(3,1) NOT NULL DEFAULT 1.0,
  `high_contrast` TINYINT NOT NULL DEFAULT 0,
  `voice_guide_enabled` TINYINT NOT NULL DEFAULT 1,
  `senior_mode` TINYINT NOT NULL DEFAULT 0,
  `locale_code` VARCHAR(16) NOT NULL DEFAULT 'zh-Hans',
  `emergency_contact_name` VARCHAR(128) NOT NULL DEFAULT '',
  `emergency_contact_phone` VARCHAR(64) NOT NULL DEFAULT '',
  `runtime_overrides_json` JSON NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY `uk_user_preferences_user_id` (`user_id`),
  KEY `idx_user_preferences_locale` (`locale_code`),
  CONSTRAINT `fk_user_preferences_user` FOREIGN KEY (`user_id`) REFERENCES `user_profiles` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reward_redemptions (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `reward_id` BIGINT NOT NULL,
  `redemption_status` VARCHAR(32) NOT NULL DEFAULT 'created',
  `stamp_cost_snapshot` INT NOT NULL DEFAULT 0,
  `qr_code` VARCHAR(255) NOT NULL DEFAULT '',
  `redeemed_at` DATETIME NULL,
  `expires_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  KEY `idx_reward_redemptions_user_id` (`user_id`),
  KEY `idx_reward_redemptions_reward_id` (`reward_id`),
  KEY `idx_reward_redemptions_status` (`redemption_status`),
  CONSTRAINT `fk_reward_redemptions_user` FOREIGN KEY (`user_id`) REFERENCES `user_profiles` (`id`),
  CONSTRAINT `fk_reward_redemptions_reward` FOREIGN KEY (`reward_id`) REFERENCES `rewards` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS seed_runs (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `seed_key` VARCHAR(128) NOT NULL,
  `description` VARCHAR(255) NOT NULL DEFAULT '',
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending',
  `executed_at` DATETIME NULL,
  `notes` TEXT NULL,
  UNIQUE KEY `uk_seed_runs_seed_key` (`seed_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
