-- Phase 33: flagship story material assets and manifest item seed.
-- Generated from docs/content-packages/east-west-war-and-coexistence/content-manifest.json.
-- All multilingual long-form copy lives in the docs manifest pack to reduce SQL encoding risk.

USE `aoxiaoyou`;

SET NAMES utf8mb4;

SET @storyline_id = (SELECT `id` FROM `storylines` WHERE `code` = 'east_west_war_and_coexistence' AND `deleted` = 0 LIMIT 1);
SET @public_base_url = 'https://tripofmacau-1301163924.cos.ap-hongkong.myqcloud.com';

INSERT INTO `story_material_packages` (
  `code`, `storyline_id`, `title_zh`, `title_zht`, `title_en`, `title_pt`,
  `summary_zh`, `summary_zht`, `historical_basis_zh`, `historical_basis_zht`,
  `literary_dramatization_zh`, `literary_dramatization_zht`,
  `local_root`, `cos_prefix`, `manifest_path`, `manifest_json`, `package_status`,
  `material_count`, `asset_count`, `story_object_count`, `created_by_admin_name`, `published_at`, `deleted`
) VALUES (
  'east_west_war_and_coexistence_package', @storyline_id, '東西方文明的戰火與共生', '東西方文明的戰火與共生', 'War and Coexistence of Eastern and Western Civilizations', 'Guerra e coexistencia das civilizacoes oriental e ocidental',
  'Five-chapter flagship story material package for the v3.0 story experience control plane.', '五章旗艦故事素材包，供 v3.0 故事體驗編排系統追蹤與復用。', 'See docs historical-checklist.md for evidence categories.', '見 historical-checklist.md：史實依據章節。',
  'See docs historical-checklist.md for dramatized motifs.', '見 historical-checklist.md：文學演繹章節。',
  'local-content/phase33/east-west-war-and-coexistence', 'miniapp/assets/phase33/east-west-war-and-coexistence', 'docs/content-packages/east-west-war-and-coexistence/content-manifest.json', JSON_OBJECT('schemaVersion', 1, 'manifestPath', 'docs/content-packages/east-west-war-and-coexistence/content-manifest.json', 'materialCount', 54), 'planned',
  54, 54, 0, 'phase33-seed', NULL, 0
) ON DUPLICATE KEY UPDATE
  `storyline_id` = VALUES(`storyline_id`),
  `title_zh` = VALUES(`title_zh`), `title_zht` = VALUES(`title_zht`), `title_en` = VALUES(`title_en`), `title_pt` = VALUES(`title_pt`),
  `summary_zh` = VALUES(`summary_zh`), `summary_zht` = VALUES(`summary_zht`),
  `historical_basis_zh` = VALUES(`historical_basis_zh`), `historical_basis_zht` = VALUES(`historical_basis_zht`),
  `literary_dramatization_zh` = VALUES(`literary_dramatization_zh`), `literary_dramatization_zht` = VALUES(`literary_dramatization_zht`),
  `local_root` = VALUES(`local_root`), `cos_prefix` = VALUES(`cos_prefix`), `manifest_path` = VALUES(`manifest_path`),
  `manifest_json` = VALUES(`manifest_json`), `package_status` = VALUES(`package_status`),
  `material_count` = VALUES(`material_count`), `asset_count` = VALUES(`asset_count`), `story_object_count` = VALUES(`story_object_count`),
  `created_by_admin_name` = VALUES(`created_by_admin_name`), `deleted` = 0;

SET @package_id = (SELECT `id` FROM `story_material_packages` WHERE `code` = 'east_west_war_and_coexistence_package' AND `deleted` = 0 LIMIT 1);

INSERT INTO `content_assets` (
  `id`, `asset_kind`, `bucket_name`, `region`, `object_key`, `canonical_url`, `mime_type`,
  `animation_subtype`, `poster_asset_id`, `fallback_asset_id`, `default_loop`, `default_autoplay`,
  `locale_code`, `original_filename`, `file_extension`, `upload_source`, `client_relative_path`, `uploaded_by_admin_name`,
  `file_size_bytes`, `checksum`, `etag`, `processing_policy_code`, `processing_status`, `processing_note`, `status`, `published_at`
) VALUES
  (333001, 'image', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/story-cover-copper-mirror.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/story-cover-copper-mirror.png'), 'image/png', NULL, NULL, NULL, 0, 0, 'zh-Hant', 'story-cover-copper-mirror.png', 'png', 'seed', 'images/story-cover-copper-mirror.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/images/story-cover-copper-mirror.png', 256), CONCAT('seed-', 333001), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333002, 'image', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/story-banner-route-map.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/story-banner-route-map.png'), 'image/png', NULL, NULL, 333001, 0, 0, 'zh-Hant', 'story-banner-route-map.png', 'png', 'seed', 'images/story-banner-route-map.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/images/story-banner-route-map.png', 256), CONCAT('seed-', 333002), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333003, 'lottie', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/lottie/route-copper-pulse.json', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/lottie/route-copper-pulse.json'), 'application/json', 'lottie-json', 333002, 333002, 1, 1, 'zh-Hant', 'route-copper-pulse.json', 'json', 'seed', 'lottie/route-copper-pulse.json', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/lottie/route-copper-pulse.json', 256), CONCAT('seed-', 333003), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333004, 'lottie', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/lottie/pickup-shimmer.json', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/lottie/pickup-shimmer.json'), 'application/json', 'lottie-json', 333007, 333007, 1, 1, 'zh-Hant', 'pickup-shimmer.json', 'json', 'seed', 'lottie/pickup-shimmer.json', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/lottie/pickup-shimmer.json', 256), CONCAT('seed-', 333004), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333005, 'lottie', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/lottie/chapter-clear.json', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/lottie/chapter-clear.json'), 'application/json', 'lottie-json', 333007, 333007, 1, 1, 'zh-Hant', 'chapter-clear.json', 'json', 'seed', 'lottie/chapter-clear.json', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/lottie/chapter-clear.json', 256), CONCAT('seed-', 333005), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333006, 'lottie', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/lottie/final-mirror-synthesis.json', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/lottie/final-mirror-synthesis.json'), 'application/json', 'lottie-json', 333007, 333007, 1, 1, 'zh-Hant', 'final-mirror-synthesis.json', 'json', 'seed', 'lottie/final-mirror-synthesis.json', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/lottie/final-mirror-synthesis.json', 256), CONCAT('seed-', 333006), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333007, 'image', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/poster-video-fallback.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/poster-video-fallback.png'), 'image/png', NULL, NULL, NULL, 0, 0, 'zh-Hant', 'poster-video-fallback.png', 'png', 'seed', 'images/poster-video-fallback.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/images/poster-video-fallback.png', 256), CONCAT('seed-', 333007), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333008, 'video', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/video/finale-recap-placeholder.mp4', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/video/finale-recap-placeholder.mp4'), 'video/mp4', NULL, 333007, 333007, 0, 0, 'zh-Hant', 'finale-recap-placeholder.mp4', 'mp4', 'seed', 'video/finale-recap-placeholder.mp4', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/video/finale-recap-placeholder.mp4', 256), CONCAT('seed-', 333008), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333009, 'audio', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/sfx-reward-unlock.mp3', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/sfx-reward-unlock.mp3'), 'audio/mpeg', NULL, NULL, NULL, 0, 0, 'zh-Hant', 'sfx-reward-unlock.mp3', 'mp3', 'seed', 'audio/sfx-reward-unlock.mp3', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/audio/sfx-reward-unlock.mp3', 256), CONCAT('seed-', 333009), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333010, 'audio', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch01-narration.mp3', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch01-narration.mp3'), 'audio/mpeg', NULL, NULL, NULL, 0, 0, 'zh-Hant', 'ch01-narration.mp3', 'mp3', 'seed', 'audio/ch01-narration.mp3', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch01-narration.mp3', 256), CONCAT('seed-', 333010), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333011, 'audio', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch02-narration.mp3', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch02-narration.mp3'), 'audio/mpeg', NULL, NULL, NULL, 0, 0, 'zh-Hant', 'ch02-narration.mp3', 'mp3', 'seed', 'audio/ch02-narration.mp3', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch02-narration.mp3', 256), CONCAT('seed-', 333011), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333012, 'audio', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch03-narration.mp3', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch03-narration.mp3'), 'audio/mpeg', NULL, NULL, NULL, 0, 0, 'zh-Hant', 'ch03-narration.mp3', 'mp3', 'seed', 'audio/ch03-narration.mp3', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch03-narration.mp3', 256), CONCAT('seed-', 333012), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333013, 'audio', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch04-narration.mp3', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch04-narration.mp3'), 'audio/mpeg', NULL, NULL, NULL, 0, 0, 'zh-Hant', 'ch04-narration.mp3', 'mp3', 'seed', 'audio/ch04-narration.mp3', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch04-narration.mp3', 256), CONCAT('seed-', 333013), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333014, 'audio', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch05-narration.mp3', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch05-narration.mp3'), 'audio/mpeg', NULL, NULL, NULL, 0, 0, 'zh-Hant', 'ch05-narration.mp3', 'mp3', 'seed', 'audio/ch05-narration.mp3', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch05-narration.mp3', 256), CONCAT('seed-', 333014), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333015, 'image', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch01-ama-coast.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch01-ama-coast.png'), 'image/png', NULL, NULL, 333001, 0, 0, 'zh-Hant', 'ch01-ama-coast.png', 'png', 'seed', 'images/heroes/ch01-ama-coast.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch01-ama-coast.png', 256), CONCAT('seed-', 333015), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333016, 'image', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch02-lilau-boundary.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch02-lilau-boundary.png'), 'image/png', NULL, NULL, 333001, 0, 0, 'zh-Hant', 'ch02-lilau-boundary.png', 'png', 'seed', 'images/heroes/ch02-lilau-boundary.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch02-lilau-boundary.png', 256), CONCAT('seed-', 333016), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333017, 'image', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch03-hill-watch.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch03-hill-watch.png'), 'image/png', NULL, NULL, 333001, 0, 0, 'zh-Hant', 'ch03-hill-watch.png', 'png', 'seed', 'images/heroes/ch03-hill-watch.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch03-hill-watch.png', 256), CONCAT('seed-', 333017), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333018, 'image', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch04-monte-fort.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch04-monte-fort.png'), 'image/png', NULL, NULL, 333001, 0, 0, 'zh-Hant', 'ch04-monte-fort.png', 'png', 'seed', 'images/heroes/ch04-monte-fort.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch04-monte-fort.png', 256), CONCAT('seed-', 333018), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333019, 'image', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch05-senado-coexistence.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch05-senado-coexistence.png'), 'image/png', NULL, NULL, 333001, 0, 0, 'zh-Hant', 'ch05-senado-coexistence.png', 'png', 'seed', 'images/heroes/ch05-senado-coexistence.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch05-senado-coexistence.png', 256), CONCAT('seed-', 333019), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333020, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch01-ming-coastal-token.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch01-ming-coastal-token.png'), 'image/png', NULL, NULL, 333004, 0, 0, 'zh-Hant', 'ch01-ming-coastal-token.png', 'png', 'seed', 'icons/pickups/ch01-ming-coastal-token.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch01-ming-coastal-token.png', 256), CONCAT('seed-', 333020), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333021, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch01-fisher-net-fragment.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch01-fisher-net-fragment.png'), 'image/png', NULL, NULL, 333004, 0, 0, 'zh-Hant', 'ch01-fisher-net-fragment.png', 'png', 'seed', 'icons/pickups/ch01-fisher-net-fragment.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch01-fisher-net-fragment.png', 256), CONCAT('seed-', 333021), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333022, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch01-tax-contract-page.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch01-tax-contract-page.png'), 'image/png', NULL, NULL, 333004, 0, 0, 'zh-Hant', 'ch01-tax-contract-page.png', 'png', 'seed', 'icons/pickups/ch01-tax-contract-page.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch01-tax-contract-page.png', 256), CONCAT('seed-', 333022), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333023, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch01-ama-mirror-fragment.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch01-ama-mirror-fragment.png'), 'image/png', NULL, NULL, 333004, 0, 0, 'zh-Hant', 'ch01-ama-mirror-fragment.png', 'png', 'seed', 'icons/pickups/ch01-ama-mirror-fragment.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch01-ama-mirror-fragment.png', 256), CONCAT('seed-', 333023), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333024, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch02-boundary-rubbing.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch02-boundary-rubbing.png'), 'image/png', NULL, NULL, 333004, 0, 0, 'zh-Hant', 'ch02-boundary-rubbing.png', 'png', 'seed', 'icons/pickups/ch02-boundary-rubbing.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch02-boundary-rubbing.png', 256), CONCAT('seed-', 333024), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333025, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch02-fort-design-page.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch02-fort-design-page.png'), 'image/png', NULL, NULL, 333004, 0, 0, 'zh-Hant', 'ch02-fort-design-page.png', 'png', 'seed', 'icons/pickups/ch02-fort-design-page.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch02-fort-design-page.png', 256), CONCAT('seed-', 333025), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333026, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch02-garrison-flask.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch02-garrison-flask.png'), 'image/png', NULL, NULL, 333004, 0, 0, 'zh-Hant', 'ch02-garrison-flask.png', 'png', 'seed', 'icons/pickups/ch02-garrison-flask.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch02-garrison-flask.png', 256), CONCAT('seed-', 333026), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333027, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch02-south-bay-mirror-fragment.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch02-south-bay-mirror-fragment.png'), 'image/png', NULL, NULL, 333004, 0, 0, 'zh-Hant', 'ch02-south-bay-mirror-fragment.png', 'png', 'seed', 'icons/pickups/ch02-south-bay-mirror-fragment.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch02-south-bay-mirror-fragment.png', 256), CONCAT('seed-', 333027), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333028, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch03-patrol-record.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch03-patrol-record.png'), 'image/png', NULL, NULL, 333004, 0, 0, 'zh-Hant', 'ch03-patrol-record.png', 'png', 'seed', 'icons/pickups/ch03-patrol-record.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch03-patrol-record.png', 256), CONCAT('seed-', 333028), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333029, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch03-mission-military-letter.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch03-mission-military-letter.png'), 'image/png', NULL, NULL, 333004, 0, 0, 'zh-Hant', 'ch03-mission-military-letter.png', 'png', 'seed', 'icons/pickups/ch03-mission-military-letter.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch03-mission-military-letter.png', 256), CONCAT('seed-', 333029), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333030, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch03-hill-defense-sketch.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch03-hill-defense-sketch.png'), 'image/png', NULL, NULL, 333004, 0, 0, 'zh-Hant', 'ch03-hill-defense-sketch.png', 'png', 'seed', 'icons/pickups/ch03-hill-defense-sketch.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch03-hill-defense-sketch.png', 256), CONCAT('seed-', 333030), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333031, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch03-hill-mirror-fragment.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch03-hill-mirror-fragment.png'), 'image/png', NULL, NULL, 333004, 0, 0, 'zh-Hant', 'ch03-hill-mirror-fragment.png', 'png', 'seed', 'icons/pickups/ch03-hill-mirror-fragment.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch03-hill-mirror-fragment.png', 256), CONCAT('seed-', 333031), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333032, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-cannonball-fragment.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-cannonball-fragment.png'), 'image/png', NULL, NULL, 333004, 0, 0, 'zh-Hant', 'ch04-cannonball-fragment.png', 'png', 'seed', 'icons/pickups/ch04-cannonball-fragment.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-cannonball-fragment.png', 256), CONCAT('seed-', 333032), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333033, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-defender-diary.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-defender-diary.png'), 'image/png', NULL, NULL, 333004, 0, 0, 'zh-Hant', 'ch04-defender-diary.png', 'png', 'seed', 'icons/pickups/ch04-defender-diary.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-defender-diary.png', 256), CONCAT('seed-', 333033), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333034, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-dutch-fleet-map.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-dutch-fleet-map.png'), 'image/png', NULL, NULL, 333004, 0, 0, 'zh-Hant', 'ch04-dutch-fleet-map.png', 'png', 'seed', 'icons/pickups/ch04-dutch-fleet-map.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-dutch-fleet-map.png', 256), CONCAT('seed-', 333034), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333035, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-guardian-oath.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-guardian-oath.png'), 'image/png', NULL, NULL, 333004, 0, 0, 'zh-Hant', 'ch04-guardian-oath.png', 'png', 'seed', 'icons/pickups/ch04-guardian-oath.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-guardian-oath.png', 256), CONCAT('seed-', 333035), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333036, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-fortress-mirror-fragment.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-fortress-mirror-fragment.png'), 'image/png', NULL, NULL, 333004, 0, 0, 'zh-Hant', 'ch04-fortress-mirror-fragment.png', 'png', 'seed', 'icons/pickups/ch04-fortress-mirror-fragment.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-fortress-mirror-fragment.png', 256), CONCAT('seed-', 333036), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333037, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch05-coexistence-declaration.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch05-coexistence-declaration.png'), 'image/png', NULL, NULL, 333004, 0, 0, 'zh-Hant', 'ch05-coexistence-declaration.png', 'png', 'seed', 'icons/pickups/ch05-coexistence-declaration.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch05-coexistence-declaration.png', 256), CONCAT('seed-', 333037), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333038, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch05-time-witness-pass.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch05-time-witness-pass.png'), 'image/png', NULL, NULL, 333004, 0, 0, 'zh-Hant', 'ch05-time-witness-pass.png', 'png', 'seed', 'icons/pickups/ch05-time-witness-pass.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch05-time-witness-pass.png', 256), CONCAT('seed-', 333038), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333039, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch05-complete-copper-mirror.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch05-complete-copper-mirror.png'), 'image/png', NULL, NULL, 333006, 0, 0, 'zh-Hant', 'ch05-complete-copper-mirror.png', 'png', 'seed', 'icons/pickups/ch05-complete-copper-mirror.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch05-complete-copper-mirror.png', 256), CONCAT('seed-', 333039), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333040, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-first-harbour-witness.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-first-harbour-witness.png'), 'image/png', NULL, NULL, 333009, 0, 0, 'zh-Hant', 'title-first-harbour-witness.png', 'png', 'seed', 'icons/titles/title-first-harbour-witness.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-first-harbour-witness.png', 256), CONCAT('seed-', 333040), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333041, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-mirror-sea-explorer.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-mirror-sea-explorer.png'), 'image/png', NULL, NULL, 333009, 0, 0, 'zh-Hant', 'title-mirror-sea-explorer.png', 'png', 'seed', 'icons/titles/title-mirror-sea-explorer.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-mirror-sea-explorer.png', 256), CONCAT('seed-', 333041), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333042, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-coast-guardian.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-coast-guardian.png'), 'image/png', NULL, NULL, 333009, 0, 0, 'zh-Hant', 'title-coast-guardian.png', 'png', 'seed', 'icons/titles/title-coast-guardian.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-coast-guardian.png', 256), CONCAT('seed-', 333042), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333043, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-south-bay-wayfarer.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-south-bay-wayfarer.png'), 'image/png', NULL, NULL, 333009, 0, 0, 'zh-Hant', 'title-south-bay-wayfarer.png', 'png', 'seed', 'icons/titles/title-south-bay-wayfarer.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-south-bay-wayfarer.png', 256), CONCAT('seed-', 333043), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333044, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-boundary-recorder.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-boundary-recorder.png'), 'image/png', NULL, NULL, 333009, 0, 0, 'zh-Hant', 'title-boundary-recorder.png', 'png', 'seed', 'icons/titles/title-boundary-recorder.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-boundary-recorder.png', 256), CONCAT('seed-', 333044), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333045, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-silent-frontier-soldier.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-silent-frontier-soldier.png'), 'image/png', NULL, NULL, 333009, 0, 0, 'zh-Hant', 'title-silent-frontier-soldier.png', 'png', 'seed', 'icons/titles/title-silent-frontier-soldier.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-silent-frontier-soldier.png', 256), CONCAT('seed-', 333045), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333046, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-hill-climber.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-hill-climber.png'), 'image/png', NULL, NULL, 333009, 0, 0, 'zh-Hant', 'title-hill-climber.png', 'png', 'seed', 'icons/titles/title-hill-climber.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-hill-climber.png', 256), CONCAT('seed-', 333046), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333047, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-hidden-sentry-finder.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-hidden-sentry-finder.png'), 'image/png', NULL, NULL, 333009, 0, 0, 'zh-Hant', 'title-hidden-sentry-finder.png', 'png', 'seed', 'icons/titles/title-hidden-sentry-finder.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-hidden-sentry-finder.png', 256), CONCAT('seed-', 333047), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333048, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-panorama-witness.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-panorama-witness.png'), 'image/png', NULL, NULL, 333009, 0, 0, 'zh-Hant', 'title-panorama-witness.png', 'png', 'seed', 'icons/titles/title-panorama-witness.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-panorama-witness.png', 256), CONCAT('seed-', 333048), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333049, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-fortress-visitor.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-fortress-visitor.png'), 'image/png', NULL, NULL, 333009, 0, 0, 'zh-Hant', 'title-fortress-visitor.png', 'png', 'seed', 'icons/titles/title-fortress-visitor.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-fortress-visitor.png', 256), CONCAT('seed-', 333049), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333050, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-battle-restorer.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-battle-restorer.png'), 'image/png', NULL, NULL, 333009, 0, 0, 'zh-Hant', 'title-battle-restorer.png', 'png', 'seed', 'icons/titles/title-battle-restorer.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-battle-restorer.png', 256), CONCAT('seed-', 333050), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333051, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-harbour-guardian-deity.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-harbour-guardian-deity.png'), 'image/png', NULL, NULL, 333009, 0, 0, 'zh-Hant', 'title-harbour-guardian-deity.png', 'png', 'seed', 'icons/titles/title-harbour-guardian-deity.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-harbour-guardian-deity.png', 256), CONCAT('seed-', 333051), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333052, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-harbour-witness-final.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-harbour-witness-final.png'), 'image/png', NULL, NULL, 333009, 0, 0, 'zh-Hant', 'title-harbour-witness-final.png', 'png', 'seed', 'icons/titles/title-harbour-witness-final.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-harbour-witness-final.png', 256), CONCAT('seed-', 333052), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333053, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-history-restoration-master.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-history-restoration-master.png'), 'image/png', NULL, NULL, 333009, 0, 0, 'zh-Hant', 'title-history-restoration-master.png', 'png', 'seed', 'icons/titles/title-history-restoration-master.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-history-restoration-master.png', 256), CONCAT('seed-', 333053), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL),
  (333054, 'icon', 'seed', 'ap-hongkong', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-harbour-history-grandmaster.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-harbour-history-grandmaster.png'), 'image/png', NULL, NULL, 333009, 0, 0, 'zh-Hant', 'title-harbour-history-grandmaster.png', 'png', 'seed', 'icons/titles/title-harbour-history-grandmaster.png', 'phase33-seed', 0, SHA2('miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-harbour-history-grandmaster.png', 256), CONCAT('seed-', 333054), 'seeded', 'planned', 'Phase 33 planned material; upload helper may replace with real COS metadata later.', 'draft', NULL)
ON DUPLICATE KEY UPDATE
  `asset_kind` = VALUES(`asset_kind`), `bucket_name` = VALUES(`bucket_name`), `region` = VALUES(`region`),
  `object_key` = VALUES(`object_key`), `canonical_url` = VALUES(`canonical_url`), `mime_type` = VALUES(`mime_type`),
  `animation_subtype` = VALUES(`animation_subtype`), `poster_asset_id` = VALUES(`poster_asset_id`), `fallback_asset_id` = VALUES(`fallback_asset_id`),
  `default_loop` = VALUES(`default_loop`), `default_autoplay` = VALUES(`default_autoplay`), `locale_code` = VALUES(`locale_code`),
  `original_filename` = VALUES(`original_filename`), `file_extension` = VALUES(`file_extension`), `upload_source` = VALUES(`upload_source`),
  `client_relative_path` = VALUES(`client_relative_path`), `uploaded_by_admin_name` = VALUES(`uploaded_by_admin_name`),
  `checksum` = VALUES(`checksum`), `etag` = VALUES(`etag`), `processing_policy_code` = VALUES(`processing_policy_code`),
  `processing_status` = VALUES(`processing_status`), `processing_note` = VALUES(`processing_note`), `status` = VALUES(`status`), `published_at` = VALUES(`published_at`);

INSERT INTO `story_material_package_items` (
  `package_id`, `item_key`, `item_type`, `asset_kind`, `target_type`, `target_id`, `target_code`, `asset_id`,
  `local_path`, `cos_object_key`, `canonical_url`, `usage_target`, `chapter_code`, `provenance_type`,
  `prompt_text`, `script_text`, `historical_basis_zh`, `historical_basis_zht`,
  `literary_dramatization_zh`, `literary_dramatization_zht`, `fallback_item_key`, `status`, `sort_order`, `deleted`
) VALUES
  (@package_id, 'story_cover_copper_mirror', 'story_cover', 'image', 'storyline', NULL, 'east_west_war_and_coexistence', 333001, 'images/story-cover-copper-mirror.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/story-cover-copper-mirror.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/story-cover-copper-mirror.png'), 'storyline.cover', 'storyline', 'ai_image_prompt', 'prompt:image-prompts#cover-banner', NULL, 'historical-checklist#route-sites', 'historical-checklist#route-sites', 'historical-checklist#copper-mirror-motif', 'historical-checklist#copper-mirror-motif', '', 'planned', 10, 0),
  (@package_id, 'story_banner_route_map', 'story_banner', 'image', 'storyline', NULL, 'east_west_war_and_coexistence', 333002, 'images/story-banner-route-map.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/story-banner-route-map.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/story-banner-route-map.png'), 'storyline.banner', 'storyline', 'ai_image_prompt', 'prompt:image-prompts#cover-banner', NULL, 'historical-checklist#route-sites', 'historical-checklist#route-sites', 'historical-checklist#route-drama', 'historical-checklist#route-drama', 'story_cover_copper_mirror', 'planned', 20, 0),
  (@package_id, 'lottie_route_copper_pulse', 'lottie_animation', 'lottie', 'storyline', NULL, 'east_west_war_and_coexistence', 333003, 'lottie/route-copper-pulse.json', 'miniapp/assets/phase33/east-west-war-and-coexistence/lottie/route-copper-pulse.json', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/lottie/route-copper-pulse.json'), 'storyline.route-pulse', 'storyline', 'lottie_fixture', 'prompt:lottie-design#route-copper-pulse', NULL, 'historical-checklist#route-sites', 'historical-checklist#route-sites', 'historical-checklist#route-drama', 'historical-checklist#route-drama', 'story_banner_route_map', 'planned', 30, 0),
  (@package_id, 'lottie_pickup_shimmer', 'lottie_animation', 'lottie', '', NULL, 'global', 333004, 'lottie/pickup-shimmer.json', 'miniapp/assets/phase33/east-west-war-and-coexistence/lottie/pickup-shimmer.json', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/lottie/pickup-shimmer.json'), 'pickup.appearance', 'global', 'lottie_fixture', 'prompt:lottie-design#pickup-shimmer', NULL, 'historical-checklist#artifact-classes', 'historical-checklist#artifact-classes', 'historical-checklist#pickup-glow', 'historical-checklist#pickup-glow', 'poster_video_fallback', 'planned', 40, 0),
  (@package_id, 'lottie_chapter_clear', 'lottie_animation', 'lottie', '', NULL, 'global', 333005, 'lottie/chapter-clear.json', 'miniapp/assets/phase33/east-west-war-and-coexistence/lottie/chapter-clear.json', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/lottie/chapter-clear.json'), 'chapter.clear-presentation', 'global', 'lottie_fixture', 'prompt:lottie-design#chapter-clear', NULL, 'historical-checklist#route-sites', 'historical-checklist#route-sites', 'historical-checklist#reward-theatre', 'historical-checklist#reward-theatre', 'poster_video_fallback', 'planned', 50, 0),
  (@package_id, 'lottie_final_mirror_synthesis', 'lottie_animation', 'lottie', 'story_chapter', NULL, 'ch05_coexistence_finale', 333006, 'lottie/final-mirror-synthesis.json', 'miniapp/assets/phase33/east-west-war-and-coexistence/lottie/final-mirror-synthesis.json', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/lottie/final-mirror-synthesis.json'), 'finale.fullscreen-synthesis', 'ch05_coexistence_finale', 'lottie_fixture', 'prompt:lottie-design#final-mirror-synthesis', NULL, 'historical-checklist#coexistence', 'historical-checklist#coexistence', 'historical-checklist#copper-mirror-motif', 'historical-checklist#copper-mirror-motif', 'poster_video_fallback', 'planned', 60, 0),
  (@package_id, 'poster_video_fallback', 'poster_fallback', 'image', 'content_asset', NULL, 'global', 333007, 'images/poster-video-fallback.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/poster-video-fallback.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/poster-video-fallback.png'), 'media.poster-fallback', 'global', 'ai_image_prompt', 'prompt:image-prompts#poster-fallback', NULL, 'historical-checklist#coexistence', 'historical-checklist#coexistence', 'historical-checklist#route-drama', 'historical-checklist#route-drama', '', 'planned', 70, 0),
  (@package_id, 'video_finale_recap_placeholder', 'video_placeholder', 'video', 'story_chapter', NULL, 'ch05_coexistence_finale', 333008, 'video/finale-recap-placeholder.mp4', 'miniapp/assets/phase33/east-west-war-and-coexistence/video/finale-recap-placeholder.mp4', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/video/finale-recap-placeholder.mp4'), 'finale.route-recap-video', 'ch05_coexistence_finale', 'script_placeholder', NULL, 'script:audio-scripts#finale-video-recap', 'historical-checklist#route-sites', 'historical-checklist#route-sites', 'historical-checklist#route-drama', 'historical-checklist#route-drama', 'poster_video_fallback', 'planned', 80, 0),
  (@package_id, 'sfx_reward_unlock', 'reward_sfx', 'audio', 'reward', NULL, 'global', 333009, 'audio/sfx-reward-unlock.mp3', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/sfx-reward-unlock.mp3', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/sfx-reward-unlock.mp3'), 'reward.unlock-sfx', 'global', 'tts_or_sfx_prompt', NULL, 'script:audio-scripts#reward-sfx', 'historical-checklist#none', 'historical-checklist#none', 'historical-checklist#reward-theatre', 'historical-checklist#reward-theatre', '', 'planned', 90, 0),
  (@package_id, 'audio_ch01_narration', 'narration_audio', 'audio', 'story_chapter', NULL, 'ch01_mirror_sea_clash', 333010, 'audio/ch01-narration.mp3', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch01-narration.mp3', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch01-narration.mp3'), 'chapter.narration', 'ch01_mirror_sea_clash', 'tts_script', NULL, 'script:audio-scripts#ch01', 'historical-checklist#early-portuguese-presence', 'historical-checklist#early-portuguese-presence', 'historical-checklist#ch01-reconstruction', 'historical-checklist#ch01-reconstruction', '', 'planned', 100, 0),
  (@package_id, 'audio_ch02_narration', 'narration_audio', 'audio', 'story_chapter', NULL, 'ch02_south_bay_boundary', 333011, 'audio/ch02-narration.mp3', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch02-narration.mp3', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch02-narration.mp3'), 'chapter.narration', 'ch02_south_bay_boundary', 'tts_script', NULL, 'script:audio-scripts#ch02', 'historical-checklist#lilau-settlement', 'historical-checklist#lilau-settlement', 'historical-checklist#ch02-boundary-drama', 'historical-checklist#ch02-boundary-drama', '', 'planned', 110, 0),
  (@package_id, 'audio_ch03_narration', 'narration_audio', 'audio', 'story_chapter', NULL, 'ch03_hill_watch', 333012, 'audio/ch03-narration.mp3', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch03-narration.mp3', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch03-narration.mp3'), 'chapter.narration', 'ch03_hill_watch', 'tts_script', NULL, 'script:audio-scripts#ch03', 'historical-checklist#church-and-hill', 'historical-checklist#church-and-hill', 'historical-checklist#ch03-watch-drama', 'historical-checklist#ch03-watch-drama', '', 'planned', 120, 0),
  (@package_id, 'audio_ch04_narration', 'narration_audio', 'audio', 'story_chapter', NULL, 'ch04_fortress_fire', 333013, 'audio/ch04-narration.mp3', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch04-narration.mp3', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch04-narration.mp3'), 'chapter.narration', 'ch04_fortress_fire', 'tts_script', NULL, 'script:audio-scripts#ch04', 'historical-checklist#dutch-attack-1622', 'historical-checklist#dutch-attack-1622', 'historical-checklist#ch04-battle-drama', 'historical-checklist#ch04-battle-drama', '', 'planned', 130, 0),
  (@package_id, 'audio_ch05_narration', 'narration_audio', 'audio', 'story_chapter', NULL, 'ch05_coexistence_finale', 333014, 'audio/ch05-narration.mp3', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch05-narration.mp3', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/audio/ch05-narration.mp3'), 'chapter.narration', 'ch05_coexistence_finale', 'tts_script', NULL, 'script:audio-scripts#ch05', 'historical-checklist#coexistence', 'historical-checklist#coexistence', 'historical-checklist#finale-witness', 'historical-checklist#finale-witness', '', 'planned', 140, 0),
  (@package_id, 'hero_ch01_ama_coast', 'chapter_hero', 'image', 'story_chapter', NULL, 'ch01_mirror_sea_clash', 333015, 'images/heroes/ch01-ama-coast.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch01-ama-coast.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch01-ama-coast.png'), 'chapter.hero', 'ch01_mirror_sea_clash', 'ai_image_prompt', 'prompt:image-prompts#chapter-heroes', NULL, 'historical-checklist#ama-temple', 'historical-checklist#ama-temple', 'historical-checklist#ch01-reconstruction', 'historical-checklist#ch01-reconstruction', 'story_cover_copper_mirror', 'planned', 150, 0),
  (@package_id, 'hero_ch02_lilau_boundary', 'chapter_hero', 'image', 'story_chapter', NULL, 'ch02_south_bay_boundary', 333016, 'images/heroes/ch02-lilau-boundary.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch02-lilau-boundary.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch02-lilau-boundary.png'), 'chapter.hero', 'ch02_south_bay_boundary', 'ai_image_prompt', 'prompt:image-prompts#chapter-heroes', NULL, 'historical-checklist#lilau-settlement', 'historical-checklist#lilau-settlement', 'historical-checklist#ch02-boundary-drama', 'historical-checklist#ch02-boundary-drama', 'story_cover_copper_mirror', 'planned', 160, 0),
  (@package_id, 'hero_ch03_hill_watch', 'chapter_hero', 'image', 'story_chapter', NULL, 'ch03_hill_watch', 333017, 'images/heroes/ch03-hill-watch.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch03-hill-watch.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch03-hill-watch.png'), 'chapter.hero', 'ch03_hill_watch', 'ai_image_prompt', 'prompt:image-prompts#chapter-heroes', NULL, 'historical-checklist#church-and-hill', 'historical-checklist#church-and-hill', 'historical-checklist#ch03-watch-drama', 'historical-checklist#ch03-watch-drama', 'story_cover_copper_mirror', 'planned', 170, 0),
  (@package_id, 'hero_ch04_monte_fort', 'chapter_hero', 'image', 'story_chapter', NULL, 'ch04_fortress_fire', 333018, 'images/heroes/ch04-monte-fort.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch04-monte-fort.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch04-monte-fort.png'), 'chapter.hero', 'ch04_fortress_fire', 'ai_image_prompt', 'prompt:image-prompts#chapter-heroes', NULL, 'historical-checklist#dutch-attack-1622', 'historical-checklist#dutch-attack-1622', 'historical-checklist#ch04-battle-drama', 'historical-checklist#ch04-battle-drama', 'story_cover_copper_mirror', 'planned', 180, 0),
  (@package_id, 'hero_ch05_senado_coexistence', 'chapter_hero', 'image', 'story_chapter', NULL, 'ch05_coexistence_finale', 333019, 'images/heroes/ch05-senado-coexistence.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch05-senado-coexistence.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/images/heroes/ch05-senado-coexistence.png'), 'chapter.hero', 'ch05_coexistence_finale', 'ai_image_prompt', 'prompt:image-prompts#chapter-heroes', NULL, 'historical-checklist#coexistence', 'historical-checklist#coexistence', 'historical-checklist#finale-witness', 'historical-checklist#finale-witness', 'story_cover_copper_mirror', 'planned', 190, 0),
  (@package_id, 'pickup_ming_coastal_token', 'pickup_icon', 'icon', 'story_chapter', NULL, 'ch01_mirror_sea_clash', 333020, 'icons/pickups/ch01-ming-coastal-token.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch01-ming-coastal-token.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch01-ming-coastal-token.png'), 'pickup.icon', 'ch01_mirror_sea_clash', 'ai_image_prompt', 'prompt:image-prompts#pickup-sheets', NULL, 'historical-checklist#artifact-classes', 'historical-checklist#artifact-classes', 'historical-checklist#pickup-fiction', 'historical-checklist#pickup-fiction', 'lottie_pickup_shimmer', 'planned', 200, 0),
  (@package_id, 'pickup_fisher_net_fragment', 'pickup_icon', 'icon', 'story_chapter', NULL, 'ch01_mirror_sea_clash', 333021, 'icons/pickups/ch01-fisher-net-fragment.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch01-fisher-net-fragment.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch01-fisher-net-fragment.png'), 'pickup.icon', 'ch01_mirror_sea_clash', 'ai_image_prompt', 'prompt:image-prompts#pickup-sheets', NULL, 'historical-checklist#coastal-community', 'historical-checklist#coastal-community', 'historical-checklist#pickup-fiction', 'historical-checklist#pickup-fiction', 'lottie_pickup_shimmer', 'planned', 210, 0),
  (@package_id, 'pickup_tax_contract_page', 'pickup_icon', 'icon', 'story_chapter', NULL, 'ch01_mirror_sea_clash', 333022, 'icons/pickups/ch01-tax-contract-page.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch01-tax-contract-page.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch01-tax-contract-page.png'), 'pickup.icon', 'ch01_mirror_sea_clash', 'ai_image_prompt', 'prompt:image-prompts#pickup-sheets', NULL, 'historical-checklist#trade-tax', 'historical-checklist#trade-tax', 'historical-checklist#pickup-fiction', 'historical-checklist#pickup-fiction', 'lottie_pickup_shimmer', 'planned', 220, 0),
  (@package_id, 'pickup_ama_mirror_fragment', 'pickup_icon', 'icon', 'story_chapter', NULL, 'ch01_mirror_sea_clash', 333023, 'icons/pickups/ch01-ama-mirror-fragment.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch01-ama-mirror-fragment.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch01-ama-mirror-fragment.png'), 'hidden-reward.icon', 'ch01_mirror_sea_clash', 'ai_image_prompt', 'prompt:image-prompts#pickup-sheets', NULL, 'historical-checklist#none', 'historical-checklist#none', 'historical-checklist#copper-mirror-motif', 'historical-checklist#copper-mirror-motif', 'lottie_pickup_shimmer', 'planned', 230, 0),
  (@package_id, 'pickup_boundary_rubbing', 'pickup_icon', 'icon', 'story_chapter', NULL, 'ch02_south_bay_boundary', 333024, 'icons/pickups/ch02-boundary-rubbing.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch02-boundary-rubbing.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch02-boundary-rubbing.png'), 'pickup.icon', 'ch02_south_bay_boundary', 'ai_image_prompt', 'prompt:image-prompts#pickup-sheets', NULL, 'historical-checklist#boundary-systems', 'historical-checklist#boundary-systems', 'historical-checklist#pickup-fiction', 'historical-checklist#pickup-fiction', 'lottie_pickup_shimmer', 'planned', 240, 0),
  (@package_id, 'pickup_fort_design_page', 'pickup_icon', 'icon', 'story_chapter', NULL, 'ch02_south_bay_boundary', 333025, 'icons/pickups/ch02-fort-design-page.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch02-fort-design-page.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch02-fort-design-page.png'), 'pickup.icon', 'ch02_south_bay_boundary', 'ai_image_prompt', 'prompt:image-prompts#pickup-sheets', NULL, 'historical-checklist#fortification', 'historical-checklist#fortification', 'historical-checklist#pickup-fiction', 'historical-checklist#pickup-fiction', 'lottie_pickup_shimmer', 'planned', 250, 0),
  (@package_id, 'pickup_garrison_flask', 'pickup_icon', 'icon', 'story_chapter', NULL, 'ch02_south_bay_boundary', 333026, 'icons/pickups/ch02-garrison-flask.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch02-garrison-flask.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch02-garrison-flask.png'), 'pickup.icon', 'ch02_south_bay_boundary', 'ai_image_prompt', 'prompt:image-prompts#pickup-sheets', NULL, 'historical-checklist#garrison-life', 'historical-checklist#garrison-life', 'historical-checklist#pickup-fiction', 'historical-checklist#pickup-fiction', 'lottie_pickup_shimmer', 'planned', 260, 0),
  (@package_id, 'pickup_south_bay_mirror_fragment', 'pickup_icon', 'icon', 'story_chapter', NULL, 'ch02_south_bay_boundary', 333027, 'icons/pickups/ch02-south-bay-mirror-fragment.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch02-south-bay-mirror-fragment.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch02-south-bay-mirror-fragment.png'), 'hidden-reward.icon', 'ch02_south_bay_boundary', 'ai_image_prompt', 'prompt:image-prompts#pickup-sheets', NULL, 'historical-checklist#none', 'historical-checklist#none', 'historical-checklist#copper-mirror-motif', 'historical-checklist#copper-mirror-motif', 'lottie_pickup_shimmer', 'planned', 270, 0),
  (@package_id, 'pickup_patrol_record', 'pickup_icon', 'icon', 'story_chapter', NULL, 'ch03_hill_watch', 333028, 'icons/pickups/ch03-patrol-record.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch03-patrol-record.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch03-patrol-record.png'), 'pickup.icon', 'ch03_hill_watch', 'ai_image_prompt', 'prompt:image-prompts#pickup-sheets', NULL, 'historical-checklist#church-and-hill', 'historical-checklist#church-and-hill', 'historical-checklist#pickup-fiction', 'historical-checklist#pickup-fiction', 'lottie_pickup_shimmer', 'planned', 280, 0),
  (@package_id, 'pickup_mission_military_letter', 'pickup_icon', 'icon', 'story_chapter', NULL, 'ch03_hill_watch', 333029, 'icons/pickups/ch03-mission-military-letter.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch03-mission-military-letter.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch03-mission-military-letter.png'), 'pickup.icon', 'ch03_hill_watch', 'ai_image_prompt', 'prompt:image-prompts#pickup-sheets', NULL, 'historical-checklist#church-and-hill', 'historical-checklist#church-and-hill', 'historical-checklist#pickup-fiction', 'historical-checklist#pickup-fiction', 'lottie_pickup_shimmer', 'planned', 290, 0),
  (@package_id, 'pickup_hill_defense_sketch', 'pickup_icon', 'icon', 'story_chapter', NULL, 'ch03_hill_watch', 333030, 'icons/pickups/ch03-hill-defense-sketch.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch03-hill-defense-sketch.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch03-hill-defense-sketch.png'), 'pickup.icon', 'ch03_hill_watch', 'ai_image_prompt', 'prompt:image-prompts#pickup-sheets', NULL, 'historical-checklist#vantage-points', 'historical-checklist#vantage-points', 'historical-checklist#pickup-fiction', 'historical-checklist#pickup-fiction', 'lottie_pickup_shimmer', 'planned', 300, 0),
  (@package_id, 'pickup_hill_mirror_fragment', 'pickup_icon', 'icon', 'story_chapter', NULL, 'ch03_hill_watch', 333031, 'icons/pickups/ch03-hill-mirror-fragment.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch03-hill-mirror-fragment.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch03-hill-mirror-fragment.png'), 'hidden-reward.icon', 'ch03_hill_watch', 'ai_image_prompt', 'prompt:image-prompts#pickup-sheets', NULL, 'historical-checklist#none', 'historical-checklist#none', 'historical-checklist#copper-mirror-motif', 'historical-checklist#copper-mirror-motif', 'lottie_pickup_shimmer', 'planned', 310, 0),
  (@package_id, 'pickup_cannonball_fragment', 'pickup_icon', 'icon', 'story_chapter', NULL, 'ch04_fortress_fire', 333032, 'icons/pickups/ch04-cannonball-fragment.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-cannonball-fragment.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-cannonball-fragment.png'), 'pickup.icon', 'ch04_fortress_fire', 'ai_image_prompt', 'prompt:image-prompts#pickup-sheets', NULL, 'historical-checklist#dutch-attack-1622', 'historical-checklist#dutch-attack-1622', 'historical-checklist#pickup-fiction', 'historical-checklist#pickup-fiction', 'lottie_pickup_shimmer', 'planned', 320, 0),
  (@package_id, 'pickup_defender_diary', 'pickup_icon', 'icon', 'story_chapter', NULL, 'ch04_fortress_fire', 333033, 'icons/pickups/ch04-defender-diary.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-defender-diary.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-defender-diary.png'), 'pickup.icon', 'ch04_fortress_fire', 'ai_image_prompt', 'prompt:image-prompts#pickup-sheets', NULL, 'historical-checklist#dutch-attack-1622', 'historical-checklist#dutch-attack-1622', 'historical-checklist#pickup-fiction', 'historical-checklist#pickup-fiction', 'lottie_pickup_shimmer', 'planned', 330, 0),
  (@package_id, 'pickup_dutch_fleet_map', 'pickup_icon', 'icon', 'story_chapter', NULL, 'ch04_fortress_fire', 333034, 'icons/pickups/ch04-dutch-fleet-map.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-dutch-fleet-map.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-dutch-fleet-map.png'), 'pickup.icon', 'ch04_fortress_fire', 'ai_image_prompt', 'prompt:image-prompts#pickup-sheets', NULL, 'historical-checklist#dutch-attack-1622', 'historical-checklist#dutch-attack-1622', 'historical-checklist#pickup-fiction', 'historical-checklist#pickup-fiction', 'lottie_pickup_shimmer', 'planned', 340, 0),
  (@package_id, 'pickup_guardian_oath', 'pickup_icon', 'icon', 'story_chapter', NULL, 'ch04_fortress_fire', 333035, 'icons/pickups/ch04-guardian-oath.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-guardian-oath.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-guardian-oath.png'), 'pickup.icon', 'ch04_fortress_fire', 'ai_image_prompt', 'prompt:image-prompts#pickup-sheets', NULL, 'historical-checklist#dutch-attack-1622', 'historical-checklist#dutch-attack-1622', 'historical-checklist#pickup-fiction', 'historical-checklist#pickup-fiction', 'lottie_pickup_shimmer', 'planned', 350, 0),
  (@package_id, 'pickup_fortress_mirror_fragment', 'pickup_icon', 'icon', 'story_chapter', NULL, 'ch04_fortress_fire', 333036, 'icons/pickups/ch04-fortress-mirror-fragment.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-fortress-mirror-fragment.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch04-fortress-mirror-fragment.png'), 'hidden-reward.icon', 'ch04_fortress_fire', 'ai_image_prompt', 'prompt:image-prompts#pickup-sheets', NULL, 'historical-checklist#none', 'historical-checklist#none', 'historical-checklist#copper-mirror-motif', 'historical-checklist#copper-mirror-motif', 'lottie_pickup_shimmer', 'planned', 360, 0),
  (@package_id, 'pickup_coexistence_declaration', 'pickup_icon', 'icon', 'story_chapter', NULL, 'ch05_coexistence_finale', 333037, 'icons/pickups/ch05-coexistence-declaration.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch05-coexistence-declaration.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch05-coexistence-declaration.png'), 'pickup.icon', 'ch05_coexistence_finale', 'ai_image_prompt', 'prompt:image-prompts#pickup-sheets', NULL, 'historical-checklist#coexistence', 'historical-checklist#coexistence', 'historical-checklist#pickup-fiction', 'historical-checklist#pickup-fiction', 'lottie_pickup_shimmer', 'planned', 370, 0),
  (@package_id, 'pickup_time_witness_pass', 'pickup_icon', 'icon', 'story_chapter', NULL, 'ch05_coexistence_finale', 333038, 'icons/pickups/ch05-time-witness-pass.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch05-time-witness-pass.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch05-time-witness-pass.png'), 'pickup.icon', 'ch05_coexistence_finale', 'ai_image_prompt', 'prompt:image-prompts#pickup-sheets', NULL, 'historical-checklist#coexistence', 'historical-checklist#coexistence', 'historical-checklist#finale-witness', 'historical-checklist#finale-witness', 'lottie_pickup_shimmer', 'planned', 380, 0),
  (@package_id, 'pickup_complete_copper_mirror', 'pickup_icon', 'icon', 'story_chapter', NULL, 'ch05_coexistence_finale', 333039, 'icons/pickups/ch05-complete-copper-mirror.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch05-complete-copper-mirror.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/pickups/ch05-complete-copper-mirror.png'), 'ultimate-reward.icon', 'ch05_coexistence_finale', 'ai_image_prompt', 'prompt:image-prompts#pickup-sheets', NULL, 'historical-checklist#none', 'historical-checklist#none', 'historical-checklist#copper-mirror-motif', 'historical-checklist#copper-mirror-motif', 'lottie_final_mirror_synthesis', 'planned', 390, 0),
  (@package_id, 'title_first_harbour_witness', 'title_icon', 'icon', 'story_chapter', NULL, 'ch01_mirror_sea_clash', 333040, 'icons/titles/title-first-harbour-witness.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-first-harbour-witness.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-first-harbour-witness.png'), 'title.icon', 'ch01_mirror_sea_clash', 'ai_image_prompt', 'prompt:image-prompts#badge-title-visual-sheet', NULL, 'historical-checklist#none', 'historical-checklist#none', 'historical-checklist#reward-theatre', 'historical-checklist#reward-theatre', 'sfx_reward_unlock', 'planned', 400, 0),
  (@package_id, 'title_mirror_sea_explorer', 'title_icon', 'icon', 'story_chapter', NULL, 'ch01_mirror_sea_clash', 333041, 'icons/titles/title-mirror-sea-explorer.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-mirror-sea-explorer.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-mirror-sea-explorer.png'), 'title.icon', 'ch01_mirror_sea_clash', 'ai_image_prompt', 'prompt:image-prompts#badge-title-visual-sheet', NULL, 'historical-checklist#none', 'historical-checklist#none', 'historical-checklist#reward-theatre', 'historical-checklist#reward-theatre', 'sfx_reward_unlock', 'planned', 410, 0),
  (@package_id, 'title_coast_guardian', 'title_icon', 'icon', 'story_chapter', NULL, 'ch01_mirror_sea_clash', 333042, 'icons/titles/title-coast-guardian.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-coast-guardian.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-coast-guardian.png'), 'title.icon', 'ch01_mirror_sea_clash', 'ai_image_prompt', 'prompt:image-prompts#badge-title-visual-sheet', NULL, 'historical-checklist#none', 'historical-checklist#none', 'historical-checklist#reward-theatre', 'historical-checklist#reward-theatre', 'sfx_reward_unlock', 'planned', 420, 0),
  (@package_id, 'title_south_bay_wayfarer', 'title_icon', 'icon', 'story_chapter', NULL, 'ch02_south_bay_boundary', 333043, 'icons/titles/title-south-bay-wayfarer.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-south-bay-wayfarer.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-south-bay-wayfarer.png'), 'title.icon', 'ch02_south_bay_boundary', 'ai_image_prompt', 'prompt:image-prompts#badge-title-visual-sheet', NULL, 'historical-checklist#none', 'historical-checklist#none', 'historical-checklist#reward-theatre', 'historical-checklist#reward-theatre', 'sfx_reward_unlock', 'planned', 430, 0),
  (@package_id, 'title_boundary_recorder', 'title_icon', 'icon', 'story_chapter', NULL, 'ch02_south_bay_boundary', 333044, 'icons/titles/title-boundary-recorder.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-boundary-recorder.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-boundary-recorder.png'), 'title.icon', 'ch02_south_bay_boundary', 'ai_image_prompt', 'prompt:image-prompts#badge-title-visual-sheet', NULL, 'historical-checklist#none', 'historical-checklist#none', 'historical-checklist#reward-theatre', 'historical-checklist#reward-theatre', 'sfx_reward_unlock', 'planned', 440, 0),
  (@package_id, 'title_silent_frontier_soldier', 'title_icon', 'icon', 'story_chapter', NULL, 'ch02_south_bay_boundary', 333045, 'icons/titles/title-silent-frontier-soldier.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-silent-frontier-soldier.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-silent-frontier-soldier.png'), 'title.icon', 'ch02_south_bay_boundary', 'ai_image_prompt', 'prompt:image-prompts#badge-title-visual-sheet', NULL, 'historical-checklist#none', 'historical-checklist#none', 'historical-checklist#reward-theatre', 'historical-checklist#reward-theatre', 'sfx_reward_unlock', 'planned', 450, 0),
  (@package_id, 'title_hill_climber', 'title_icon', 'icon', 'story_chapter', NULL, 'ch03_hill_watch', 333046, 'icons/titles/title-hill-climber.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-hill-climber.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-hill-climber.png'), 'title.icon', 'ch03_hill_watch', 'ai_image_prompt', 'prompt:image-prompts#badge-title-visual-sheet', NULL, 'historical-checklist#none', 'historical-checklist#none', 'historical-checklist#reward-theatre', 'historical-checklist#reward-theatre', 'sfx_reward_unlock', 'planned', 460, 0),
  (@package_id, 'title_hidden_sentry_finder', 'title_icon', 'icon', 'story_chapter', NULL, 'ch03_hill_watch', 333047, 'icons/titles/title-hidden-sentry-finder.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-hidden-sentry-finder.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-hidden-sentry-finder.png'), 'title.icon', 'ch03_hill_watch', 'ai_image_prompt', 'prompt:image-prompts#badge-title-visual-sheet', NULL, 'historical-checklist#none', 'historical-checklist#none', 'historical-checklist#reward-theatre', 'historical-checklist#reward-theatre', 'sfx_reward_unlock', 'planned', 470, 0),
  (@package_id, 'title_panorama_witness', 'title_icon', 'icon', 'story_chapter', NULL, 'ch03_hill_watch', 333048, 'icons/titles/title-panorama-witness.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-panorama-witness.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-panorama-witness.png'), 'title.icon', 'ch03_hill_watch', 'ai_image_prompt', 'prompt:image-prompts#badge-title-visual-sheet', NULL, 'historical-checklist#none', 'historical-checklist#none', 'historical-checklist#reward-theatre', 'historical-checklist#reward-theatre', 'sfx_reward_unlock', 'planned', 480, 0),
  (@package_id, 'title_fortress_visitor', 'title_icon', 'icon', 'story_chapter', NULL, 'ch04_fortress_fire', 333049, 'icons/titles/title-fortress-visitor.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-fortress-visitor.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-fortress-visitor.png'), 'title.icon', 'ch04_fortress_fire', 'ai_image_prompt', 'prompt:image-prompts#badge-title-visual-sheet', NULL, 'historical-checklist#none', 'historical-checklist#none', 'historical-checklist#reward-theatre', 'historical-checklist#reward-theatre', 'sfx_reward_unlock', 'planned', 490, 0),
  (@package_id, 'title_battle_restorer', 'title_icon', 'icon', 'story_chapter', NULL, 'ch04_fortress_fire', 333050, 'icons/titles/title-battle-restorer.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-battle-restorer.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-battle-restorer.png'), 'title.icon', 'ch04_fortress_fire', 'ai_image_prompt', 'prompt:image-prompts#badge-title-visual-sheet', NULL, 'historical-checklist#none', 'historical-checklist#none', 'historical-checklist#reward-theatre', 'historical-checklist#reward-theatre', 'sfx_reward_unlock', 'planned', 500, 0),
  (@package_id, 'title_harbour_guardian_deity', 'title_icon', 'icon', 'story_chapter', NULL, 'ch04_fortress_fire', 333051, 'icons/titles/title-harbour-guardian-deity.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-harbour-guardian-deity.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-harbour-guardian-deity.png'), 'title.icon', 'ch04_fortress_fire', 'ai_image_prompt', 'prompt:image-prompts#badge-title-visual-sheet', NULL, 'historical-checklist#none', 'historical-checklist#none', 'historical-checklist#reward-theatre', 'historical-checklist#reward-theatre', 'sfx_reward_unlock', 'planned', 510, 0),
  (@package_id, 'title_harbour_witness_final', 'title_icon', 'icon', 'story_chapter', NULL, 'ch05_coexistence_finale', 333052, 'icons/titles/title-harbour-witness-final.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-harbour-witness-final.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-harbour-witness-final.png'), 'title.icon', 'ch05_coexistence_finale', 'ai_image_prompt', 'prompt:image-prompts#badge-title-visual-sheet', NULL, 'historical-checklist#none', 'historical-checklist#none', 'historical-checklist#reward-theatre', 'historical-checklist#reward-theatre', 'sfx_reward_unlock', 'planned', 520, 0),
  (@package_id, 'title_history_restoration_master', 'title_icon', 'icon', 'story_chapter', NULL, 'ch05_coexistence_finale', 333053, 'icons/titles/title-history-restoration-master.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-history-restoration-master.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-history-restoration-master.png'), 'title.icon', 'ch05_coexistence_finale', 'ai_image_prompt', 'prompt:image-prompts#badge-title-visual-sheet', NULL, 'historical-checklist#none', 'historical-checklist#none', 'historical-checklist#reward-theatre', 'historical-checklist#reward-theatre', 'sfx_reward_unlock', 'planned', 530, 0),
  (@package_id, 'title_harbour_history_grandmaster', 'title_icon', 'icon', 'story_chapter', NULL, 'ch05_coexistence_finale', 333054, 'icons/titles/title-harbour-history-grandmaster.png', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-harbour-history-grandmaster.png', CONCAT(@public_base_url, '/', 'miniapp/assets/phase33/east-west-war-and-coexistence/icons/titles/title-harbour-history-grandmaster.png'), 'title.icon', 'ch05_coexistence_finale', 'ai_image_prompt', 'prompt:image-prompts#badge-title-visual-sheet', NULL, 'historical-checklist#none', 'historical-checklist#none', 'historical-checklist#reward-theatre', 'historical-checklist#reward-theatre', 'sfx_reward_unlock', 'planned', 540, 0)
ON DUPLICATE KEY UPDATE
  `item_type` = VALUES(`item_type`), `asset_kind` = VALUES(`asset_kind`), `target_type` = VALUES(`target_type`),
  `target_id` = VALUES(`target_id`), `target_code` = VALUES(`target_code`), `asset_id` = VALUES(`asset_id`),
  `local_path` = VALUES(`local_path`), `cos_object_key` = VALUES(`cos_object_key`), `canonical_url` = VALUES(`canonical_url`),
  `usage_target` = VALUES(`usage_target`), `chapter_code` = VALUES(`chapter_code`), `provenance_type` = VALUES(`provenance_type`),
  `prompt_text` = VALUES(`prompt_text`), `script_text` = VALUES(`script_text`),
  `historical_basis_zh` = VALUES(`historical_basis_zh`), `historical_basis_zht` = VALUES(`historical_basis_zht`),
  `literary_dramatization_zh` = VALUES(`literary_dramatization_zh`), `literary_dramatization_zht` = VALUES(`literary_dramatization_zht`),
  `fallback_item_key` = VALUES(`fallback_item_key`), `status` = VALUES(`status`), `sort_order` = VALUES(`sort_order`), `deleted` = 0;

UPDATE `story_material_packages` p
SET
  `material_count` = (SELECT COUNT(*) FROM `story_material_package_items` i WHERE i.`package_id` = p.`id` AND i.`deleted` = 0),
  `asset_count` = (SELECT COUNT(*) FROM `story_material_package_items` i WHERE i.`package_id` = p.`id` AND i.`deleted` = 0 AND i.`asset_id` IS NOT NULL),
  `story_object_count` = (SELECT COUNT(*) FROM `story_material_package_items` i WHERE i.`package_id` = p.`id` AND i.`deleted` = 0 AND i.`target_type` <> '')
WHERE p.`id` = @package_id;

INSERT INTO `seed_runs` (`seed_key`, `description`, `status`, `executed_at`, `notes`)
VALUES ('phase33-flagship-material-assets', 'Phase 33 flagship story material asset and package item seed', 'completed', NOW(), 'Deterministic planned assets and package item provenance for east_west_war_and_coexistence_package')
ON DUPLICATE KEY UPDATE
  `description` = VALUES(`description`), `status` = VALUES(`status`), `executed_at` = VALUES(`executed_at`), `notes` = VALUES(`notes`);
