export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/map/index',
    'pages/map/indoor/index',
    'pages/tips/index',
    'pages/tips/notifications/index',
    'pages/tips/publish/index',
    'pages/tips/detail/index',
    'pages/discover/index',
    'pages/story/index',
    'pages/stamps/index',
    'pages/rewards/index',
    'pages/profile/index',
    'pages/settings/index',
    'pages/senior/index',
  ],
  tabBar: {
    custom: false,
    color: '#A0AEC0',
    selectedColor: '#FFB6C1',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首頁',
        iconPath: 'assets/tabbar/home.png',
        selectedIconPath: 'assets/tabbar/home-active.png',
      },
      {
        pagePath: 'pages/map/index',
        text: '探索',
        iconPath: 'assets/tabbar/map.png',
        selectedIconPath: 'assets/tabbar/map-active.png',
      },
      {
        pagePath: 'pages/discover/index',
        text: '發現',
        iconPath: 'assets/tabbar/discover.png',
        selectedIconPath: 'assets/tabbar/discover-active.png',
      },
      {
        pagePath: 'pages/tips/index',
        text: '秘籍',
        iconPath: 'assets/tabbar/tips.png',
        selectedIconPath: 'assets/tabbar/tips-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/tabbar/profile.png',
        selectedIconPath: 'assets/tabbar/profile-active.png',
      },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    backgroundColor: '#FFFAF0',
    navigationBarBackgroundColor: '#FFFAF0',
    navigationBarTitleText: '澳小遊',
    navigationBarTextStyle: 'black',
    navigationStyle: 'default',
  },
  permission: {
    'scope.userLocation': {
      desc: '您的位置信息将用于澳小遊小程序的定位探索。',
    },
  },
  requiredPrivateInfos: ['getLocation', 'onLocationChange'],
  requiredBackgroundModes: ['location'],
  sitemapLocation: 'sitemap.json',
})
