import {
  AppUserProfile,
  ArrivalExperience,
  CheckinResult,
  DiscoverCardItem,
  PoiItem,
  RewardItem,
  StampItem,
  StorylineItem,
  TipArticleItem,
} from '../types/game'

export const amapConfig = {
  key: '6fea5cb20fa631562465356be078d086',
  securityJsCode: '',
  defaultCity: '澳门',
  defaultCityCode: '810000',
  defaultCenter: {
    latitude: 22.1987,
    longitude: 113.5439,
  },
}

export const mockUserProfile: AppUserProfile = {
  userId: 'guest-user-macau-001',
  nickname: '未命名旅人',
  avatarUrl: '',
  isGuest: true,
  openId: '',
  level: 3,
  title: '澳門見習生',
  totalStamps: 5,
  currentExp: 180,
  nextLevelExp: 260,
  interfaceMode: 'standard',
  fontScale: 1,
  highContrast: false,
  voiceGuideEnabled: true,
  unlockedStorylines: 2,
  badges: ['歷史愛好者'],
}

export const mockPois: PoiItem[] = [
  {
    id: 1,
    name: '大三巴牌坊',
    subtitle: '東西方戰事 · 第一站',
    icon: '🏛️',
    latitude: 22.197546,
    longitude: 113.540854,
    gcj02Latitude: 22.197546,
    gcj02Longitude: 113.540854,
    address: '花王堂區炮台山下',
    geofenceRadius: 50,
    triggerRadius: 50,
    difficulty: 'easy',
    category: '歷史遺跡',
    district: '澳門半島',
    storyLineId: 2,
    storyName: '東西方戰事',
    description: '澳門最具代表性的遺跡，也是新手最容易完成的第一枚足跡章。',
    checkInMethod: 'gps',
    staySeconds: 30,
    rewardStampId: 101,
    tags: ['熱門', '地標', '故事起點'],
    coverColor: '#ffd9c2',
  },
  {
    id: 2,
    name: '議事亭前地',
    subtitle: '城市節點 · 打卡廣場',
    icon: '🏟️',
    latitude: 22.193675,
    longitude: 113.540338,
    gcj02Latitude: 22.193675,
    gcj02Longitude: 113.540338,
    address: '大堂區議事亭前地',
    geofenceRadius: 60,
    triggerRadius: 60,
    difficulty: 'easy',
    category: '廣場',
    district: '澳門半島',
    storyLineId: 2,
    storyName: '東西方戰事',
    description: '商業與文化交錯的中心地帶，可作為城市探索任務的匯流點。',
    checkInMethod: 'gps',
    staySeconds: 30,
    rewardStampId: 102,
    tags: ['拍照點', '開放空間'],
    coverColor: '#dff3ff',
  },
  {
    id: 3,
    name: '媽閣廟',
    subtitle: '海上絲路 · 起航點',
    icon: '🛕',
    latitude: 22.18684,
    longitude: 113.53159,
    gcj02Latitude: 22.18684,
    gcj02Longitude: 113.53159,
    address: '風順堂區媽閣上街',
    geofenceRadius: 80,
    triggerRadius: 80,
    difficulty: 'medium',
    category: '廟宇',
    district: '澳門半島',
    storyLineId: 1,
    storyName: '海上絲路',
    description: '澳門地名的起源地，海上絲路故事線的序章會在這裡自動展開。',
    checkInMethod: 'gps',
    staySeconds: 60,
    rewardStampId: 103,
    tags: ['文化', '語音導覽', '長者友好'],
    coverColor: '#e9defc',
  },
  {
    id: 4,
    name: '港務局大樓',
    subtitle: '海上絲路 · 摩爾回響',
    icon: '🏰',
    latitude: 22.185784,
    longitude: 113.533329,
    gcj02Latitude: 22.185784,
    gcj02Longitude: 113.533329,
    address: '媽閣河邊新街',
    geofenceRadius: 60,
    triggerRadius: 60,
    difficulty: 'medium',
    category: '歷史建築',
    district: '澳門半島',
    storyLineId: 1,
    storyName: '海上絲路',
    description: '故事中段會在此解鎖角色回憶片段與特殊故事章。',
    checkInMethod: 'gps',
    staySeconds: 45,
    rewardStampId: 104,
    tags: ['建築', '打卡連線'],
    coverColor: '#f8ebc8',
  },
  {
    id: 5,
    name: '玫瑰堂',
    subtitle: '東西方戰事 · 信仰篇章',
    icon: '⛪',
    latitude: 22.193901,
    longitude: 113.540507,
    gcj02Latitude: 22.193901,
    gcj02Longitude: 113.540507,
    address: '板樟堂前地',
    geofenceRadius: 50,
    triggerRadius: 50,
    difficulty: 'easy',
    category: '教堂',
    district: '澳門半島',
    storyLineId: 2,
    storyName: '東西方戰事',
    description: '適合作為城市廣場與歷史故事雙線結合的中途停靠點。',
    checkInMethod: 'gps',
    staySeconds: 30,
    rewardStampId: 105,
    tags: ['宗教', '故事章節'],
    coverColor: '#ffe5ef',
  },
]

export const mockStorylines: StorylineItem[] = [
  {
    id: 1,
    name: '海上絲路',
    nameEn: 'Maritime Silk Road',
    description: '從媽閣到港務局，感受澳門如何由港灣走向世界。',
    icon: '🚢',
    coverColor: '#7bb9ff',
    totalChapters: 6,
    completedChapters: 2,
    estimatedTime: '2-3小時',
    difficulty: 'easy',
    poiIds: [3, 4],
    chapterTitles: ['序章：潮汐與信仰', '第一章：海風來信', '第二章：摩爾城影'],
    progress: 34,
    rewardBadge: '航海學徒',
  },
  {
    id: 2,
    name: '東西方戰事',
    nameEn: 'East Meets West',
    description: '從大三巴到玫瑰堂，見證不同文明如何在城中交匯。',
    icon: '⚔️',
    coverColor: '#ff9f92',
    totalChapters: 8,
    completedChapters: 1,
    estimatedTime: '3-4小時',
    difficulty: 'medium',
    poiIds: [1, 2, 5],
    chapterTitles: ['序章：城牆之外', '第一章：火炮回聲', '第二章：廣場與教堂'],
    progress: 18,
    rewardBadge: '歷史見證者',
  },
]

export const mockStamps: StampItem[] = [
  { id: 101, type: 'location', name: '大三巴足跡章', description: '抵達大三巴牌坊', icon: '🏛️', collected: true, collectedAt: '2026-04-06T10:30:00+08:00', poiId: 1, rarity: 'common' },
  { id: 102, type: 'location', name: '議事亭足跡章', description: '抵達議事亭前地', icon: '🏟️', collected: true, collectedAt: '2026-04-06T11:05:00+08:00', poiId: 2, rarity: 'common' },
  { id: 103, type: 'story', name: '絲路序章章', description: '完成海上絲路序章', icon: '📖', collected: true, collectedAt: '2026-04-06T12:30:00+08:00', storyId: 1, rarity: 'rare' },
  { id: 104, type: 'mission', name: '初探澳門', description: '完成 3 枚足跡章', icon: '🎯', collected: true, collectedAt: '2026-04-06T13:00:00+08:00', rarity: 'common' },
  { id: 105, type: 'secret', name: '玫瑰堂回響', description: '夜色模式下完成一次故事觸發', icon: '🌙', collected: false, poiId: 5, rarity: 'epic' },
]

export const mockRewards: RewardItem[] = [
  { id: 1, name: '澳門老城明信片', subtitle: '實體兌換', icon: '💌', stampCost: 4, inventory: 128, status: 'available', description: '收集足跡章即可兌換一套主題明信片。', highlight: 'MVP 可先走到店核銷' },
  { id: 2, name: '海上絲路限定徽章', subtitle: '虛擬收藏', icon: '🪙', stampCost: 6, inventory: 999, status: 'available', description: '完成故事線里程碑後可解鎖頭像框與稱號。', highlight: '適合遊戲化留存' },
  { id: 3, name: '葡式蛋撻優惠券', subtitle: '合作商戶', icon: '🧁', stampCost: 8, inventory: 26, status: 'coming_soon', description: '先以 Mock 形式展示，後續接入真實商戶資源。', highlight: '商業化預留' },
]

export const mockDiscoverCards: DiscoverCardItem[] = [
  { id: 201, title: '福隆新街夜遊活動', subtitle: '活動推薦', description: '夜間限定導覽，沿著老街點亮故事節點與章節彩蛋。', tag: '今晚可參加', icon: '🌃', type: 'activity', district: '澳門半島', actionText: '查看活動', coverColor: '#ffe2ef' },
  { id: 202, title: '葡式蛋撻合作商戶', subtitle: '商戶推薦', description: '打卡兌換合作店優惠券，形成獎勵兌換與商業閉環。', tag: '徽章兌換', icon: '🧁', type: 'merchant', district: '議事亭周邊', actionText: '去兌換', coverColor: '#fff0c8' },
  { id: 203, title: '本週熱點打卡榜', subtitle: '熱門足跡', description: '大三巴、玫瑰堂與媽閣廟仍是遊客最愛的三大任務點。', tag: '熱度上升', icon: '🔥', type: 'checkin', district: '歷史城區', actionText: '跟著打卡', coverColor: '#dff3ff' },
]

export const mockTipArticles: TipArticleItem[] = [
  { id: 301, title: '第一次來澳門怎麼玩最順？', summary: '用 2 條故事線串起歷史城區，不走回頭路也能快速收章。', coverColor: '#ffe4ef', category: '新手攻略', author: '澳小遊編輯部', likes: 128, saves: 94, readMinutes: 5, tags: ['路線', '新手', '打卡'] },
  { id: 302, title: '長者友好的半日慢遊路線', summary: '集中在媽閣與議事亭周邊，節奏慢、步行短，適合語音導覽模式。', coverColor: '#e8f7ff', category: '慢遊推薦', author: '城市導覽官', likes: 86, saves: 73, readMinutes: 4, tags: ['長者模式', '慢遊', '語音'] },
  { id: 303, title: '澳門拍照最出片的 5 個點', summary: '從大三巴正面到玫瑰堂側街，附最佳光線時間與取景提醒。', coverColor: '#fff3cf', category: '拍照秘籍', author: '旅拍愛好者', likes: 211, saves: 157, readMinutes: 6, tags: ['拍照', '攻略', '熱門'] },
]

export const mockArrivalExperiences: Record<number, ArrivalExperience> = {
  1: { poiId: 1, title: '你已抵達大三巴牌坊', narrative: '火炮與鐘聲在城牆外回響，東西方故事線在這裡正式交會。', audioTitle: '大三巴導覽音頻', audioDuration: '01:28', rewardLabel: '解鎖足跡章 + 東西方戰事主線', canManualCheckin: true },
  2: { poiId: 2, title: '你已抵達議事亭前地', narrative: '廣場作為城市節點，最適合串接後續獎勵與商戶探索。', audioTitle: '議事亭城市播報', audioDuration: '01:10', rewardLabel: '解鎖城市廣場章', canManualCheckin: true },
  3: { poiId: 3, title: '你已抵達媽閣廟', narrative: '海上絲路的序章在這裡開啟，信仰與航海記憶一同甦醒。', audioTitle: '媽閣廟海風導覽', audioDuration: '01:42', rewardLabel: '解鎖絲路序章章', canManualCheckin: false },
  4: { poiId: 4, title: '你已抵達港務局大樓', narrative: '摩爾建築的曲線藏著海港城市的繁華與過往。', audioTitle: '港務局建築導覽', audioDuration: '01:18', rewardLabel: '解鎖航海回響章', canManualCheckin: true },
  5: { poiId: 5, title: '你已抵達玫瑰堂', narrative: '信仰篇章在鐘聲中推進，也為夜遊玩法預留了特殊彩蛋。', audioTitle: '玫瑰堂故事導覽', audioDuration: '01:24', rewardLabel: '解鎖玫瑰堂回響', canManualCheckin: true },
}

export const mockCheckinResults: Record<number, CheckinResult> = {
  1: { success: true, poiId: 1, poiName: '大三巴牌坊', stampId: 101, stampName: '大三巴足跡章', experienceGained: 30, triggerMode: 'gps', unlockedStorylineId: 2 },
  2: { success: true, poiId: 2, poiName: '議事亭前地', stampId: 102, stampName: '議事亭足跡章', experienceGained: 20, triggerMode: 'gps' },
  3: { success: true, poiId: 3, poiName: '媽閣廟', stampId: 103, stampName: '絲路序章章', experienceGained: 40, triggerMode: 'gps', unlockedStorylineId: 1 },
  4: { success: true, poiId: 4, poiName: '港務局大樓', stampId: 104, stampName: '航海回響章', experienceGained: 36, triggerMode: 'gps' },
  5: { success: true, poiId: 5, poiName: '玫瑰堂', stampId: 105, stampName: '玫瑰堂回響', experienceGained: 24, triggerMode: 'gps' },
}
