import {
  AppUserProfile,
  ArrivalExperience,
  CheckinResult,
  CityProgressItem,
  DiscoverCardItem,
  NotificationItem,
  PoiItem,
  RewardItem,
  StampItem,
  StorylineItem,
  TipArticleItem,
  TravelRecommendation,
} from '../types/game'

export const amapConfig = {
  key: '6fea5cb20fa631562465356be078d086',
  securityJsCode: '',
  defaultCity: '澳门',
  defaultCityCode: '810000',
  defaultCenter: {
    latitude: 22.1987,
    longitude: 113.5439,
  },
}

export const mockUserProfile: AppUserProfile = {
  userId: 'guest-user-macau-001',
  nickname: '未命名旅人',
  avatarUrl: '',
  isGuest: true,
  openId: '',
  level: 3,
  title: '澳門見習生',
  totalStamps: 5,
  currentExp: 180,
  nextLevelExp: 260,
  interfaceMode: 'standard',
  fontScale: 1,
  highContrast: false,
  voiceGuideEnabled: true,
  unlockedStorylines: 2,
  badges: ['歷史愛好者'],
  currentCityId: 'macau',
}

export const mockCities: CityProgressItem[] = [
  {
    id: 'macau',
    name: '澳門半島',
    subtitle: '世界遺產與街巷故事',
    coverColor: '#ffd9e5',
    unlocked: true,
    firstUnlockedAt: '2026-04-06T09:30:00+08:00',
    explorationProgress: 62,
    titleReward: '老城尋章者',
    landmarkCount: 8,
  },
  {
    id: 'taipa',
    name: '氹仔舊城區',
    subtitle: '美食與小巷慢遊',
    coverColor: '#dff7ef',
    unlocked: false,
    explorationProgress: 0,
    titleReward: '慢遊收藏家',
    landmarkCount: 6,
  },
  {
    id: 'coloane',
    name: '路環海岸',
    subtitle: '海風步道與靜謐教堂',
    coverColor: '#dfeaff',
    unlocked: false,
    explorationProgress: 0,
    titleReward: '海風觀察員',
    landmarkCount: 5,
  },
]

export const mockPois: PoiItem[] = [
  {
    id: 1,
    name: '大三巴牌坊',
    subtitle: '東西方戰事 · 第一站',
    icon: '🏛️',
    latitude: 22.197546,
    longitude: 113.540854,
    gcj02Latitude: 22.197546,
    gcj02Longitude: 113.540854,
    address: '花王堂區炮台山下',
    geofenceRadius: 50,
    triggerRadius: 50,
    difficulty: 'easy',
    category: '歷史遺跡',
    district: '澳門半島',
    storyLineId: 2,
    storyName: '東西方戰事',
    description: '澳門最具代表性的遺跡，也是新手最容易完成的第一枚足跡章。',
    checkInMethod: 'gps',
    staySeconds: 30,
    rewardStampId: 101,
    tags: ['熱門', '地標', '故事起點'],
    coverColor: '#ffd9c2',
    cityId: 'macau',
  },
  {
    id: 2,
    name: '議事亭前地',
    subtitle: '城市節點 · 打卡廣場',
    icon: '🏟️',
    latitude: 22.193675,
    longitude: 113.540338,
    gcj02Latitude: 22.193675,
    gcj02Longitude: 113.540338,
    address: '大堂區議事亭前地',
    geofenceRadius: 60,
    triggerRadius: 60,
    difficulty: 'easy',
    category: '廣場',
    district: '澳門半島',
    storyLineId: 2,
    storyName: '東西方戰事',
    description: '商業與文化交錯的中心地帶，可作為城市探索任務的匯流點。',
    checkInMethod: 'gps',
    staySeconds: 30,
    rewardStampId: 102,
    tags: ['拍照點', '開放空間'],
    coverColor: '#dff3ff',
    cityId: 'macau',
  },
  {
    id: 3,
    name: '媽閣廟',
    subtitle: '海上絲路 · 起航點',
    icon: '🛕',
    latitude: 22.18684,
    longitude: 113.53159,
    gcj02Latitude: 22.18684,
    gcj02Longitude: 113.53159,
    address: '風順堂區媽閣上街',
    geofenceRadius: 80,
    triggerRadius: 80,
    difficulty: 'medium',
    category: '廟宇',
    district: '澳門半島',
    storyLineId: 1,
    storyName: '海上絲路',
    description: '澳門地名的起源地，海上絲路故事線的序章會在這裡自動展開。',
    checkInMethod: 'gps',
    staySeconds: 60,
    rewardStampId: 103,
    tags: ['文化', '語音導覽', '長者友好'],
    coverColor: '#e9defc',
    cityId: 'macau',
  },
  {
    id: 4,
    name: '龍環葡韻',
    subtitle: '氹仔慢遊 · 葡式風景',
    icon: '🏘️',
    latitude: 22.1563,
    longitude: 113.5606,
    gcj02Latitude: 22.1563,
    gcj02Longitude: 113.5606,
    address: '氹仔海邊馬路',
    geofenceRadius: 60,
    triggerRadius: 60,
    difficulty: 'easy',
    category: '博物館',
    district: '氹仔',
    storyLineId: 3,
    storyName: '巷弄慢時光',
    description: '薄荷色小屋沿着海边排开，最适合拍一组柔和色系的旅途照片。',
    checkInMethod: 'gps',
    staySeconds: 45,
    rewardStampId: 106,
    tags: ['慢遊', '拍照', '新城市'],
    coverColor: '#d5f3ea',
    cityId: 'taipa',
  },
  {
    id: 5,
    name: '黑沙海灘',
    subtitle: '路環海岸 · 海風序章',
    icon: '🏖️',
    latitude: 22.1197,
    longitude: 113.5695,
    gcj02Latitude: 22.1197,
    gcj02Longitude: 113.5695,
    address: '路環黑沙海灘',
    geofenceRadius: 90,
    triggerRadius: 90,
    difficulty: 'medium',
    category: '海岸',
    district: '路環',
    storyLineId: 4,
    storyName: '海風與燈塔',
    description: '黑色細沙和海浪會把步行節奏放慢，適合安排一段長呼吸的海岸旅程。',
    checkInMethod: 'gps',
    staySeconds: 60,
    rewardStampId: 107,
    tags: ['海風', '放鬆', '城市解鎖'],
    coverColor: '#dfe9ff',
    cityId: 'coloane',
  },
]

export const mockStorylines: StorylineItem[] = [
  {
    id: 1,
    name: '海上絲路',
    nameEn: 'Maritime Silk Road',
    description: '從媽閣到港口，跟著海風走進澳門最早的城市記憶。',
    icon: '🚢',
    coverColor: '#7bb9ff',
    totalChapters: 4,
    completedChapters: 2,
    estimatedTime: '2-3小時',
    difficulty: 'easy',
    poiIds: [3],
    chapterTitles: ['序章：潮汐與信仰', '第一章：海風來信', '第二章：港灣回聲', '終章：遠航夜色'],
    progress: 50,
    rewardBadge: '航海學徒',
    moodTags: ['海風', '歷史', '慢遊'],
    chapters: [
      { id: 1011, title: '序章：潮汐與信仰', summary: '從媽閣開始認識澳門的起源。', detail: '香火、潮汐與靠岸的故事，讓這裡成為旅人理解澳門的第一把鑰匙。', achievement: '獲得「絲路序章章」', collectible: '潮汐明信片', locationName: '媽閣廟', locked: false },
      { id: 1012, title: '第一章：海風來信', summary: '沿着港灣理解古老航線。', detail: '從海邊步道慢慢走，能看見昔日船影留下的痕跡。', achievement: '解鎖港灣對話', collectible: '航海筆記殘頁', locationName: '媽閣周邊', locked: false },
      { id: 1013, title: '第二章：港灣回聲', summary: '更多船影與人聲在等你靠近。', detail: '完成前兩章後，港灣記憶會逐漸完整，並出現新的收集線索。', achievement: '解鎖海風徽記', collectible: '海港徽章', locationName: '港灣步道', locked: true },
      { id: 1014, title: '終章：遠航夜色', summary: '夜色裡的海風把故事吹到更遠。', detail: '完成整條主線後，可得到適合夜遊的紀念稱號。', achievement: '稱號：航路記錄者', collectible: '夜航星圖', locationName: '夜間港岸', locked: true },
    ],
  },
  {
    id: 2,
    name: '東西方戰事',
    nameEn: 'East Meets West',
    description: '從大三巴到玫瑰堂，感受不同文明如何在城中交匯。',
    icon: '⚔️',
    coverColor: '#ffb6c1',
    totalChapters: 4,
    completedChapters: 1,
    estimatedTime: '3-4小時',
    difficulty: 'medium',
    poiIds: [1, 2],
    chapterTitles: ['序章：城牆之外', '第一章：火炮回聲', '第二章：廣場與教堂', '終章：和平之門'],
    progress: 25,
    rewardBadge: '歷史見證者',
    moodTags: ['建築', '戰事', '文化'],
    chapters: [
      { id: 1021, title: '序章：城牆之外', summary: '站在大三巴前，讀懂城市傷痕。', detail: '風吹過殘牆，也把往昔的聲音帶回眼前。', achievement: '獲得「大三巴足跡章」', collectible: '城牆拓片', locationName: '大三巴牌坊', locked: false },
      { id: 1022, title: '第一章：火炮回聲', summary: '跟著遺跡尋找戰事留下的回音。', detail: '沿着石階與視線往高處走，故事會逐漸完整。', achievement: '解鎖戰事旁白', collectible: '炮台徽印', locationName: '炮台山一帶', locked: false },
      { id: 1023, title: '第二章：廣場與教堂', summary: '廣場、人群與鐘聲拼出另一種節奏。', detail: '在議事亭前地與教堂之間，城市開始從對抗走向交會。', achievement: '解鎖和平線索', collectible: '玫瑰花窗碎片', locationName: '議事亭前地', locked: true },
      { id: 1024, title: '終章：和平之門', summary: '所有線索都指向新的理解。', detail: '完成整條主線後，你會得到能代表這段旅程的稱號與收藏。', achievement: '稱號：古城見證人', collectible: '和平紀念封', locationName: '玫瑰堂', locked: true },
    ],
  },
  {
    id: 3,
    name: '巷弄慢時光',
    nameEn: 'Taipa Leisure Walk',
    description: '氹仔旧城区的色彩、甜点和静静发光的小巷都适合慢慢收集。',
    icon: '🍮',
    coverColor: '#c9f4df',
    totalChapters: 3,
    completedChapters: 0,
    estimatedTime: '1.5-2小時',
    difficulty: 'easy',
    poiIds: [4],
    chapterTitles: ['序章：彩色外牆', '第一章：甜點小徑', '終章：薄暮散步'],
    progress: 0,
    rewardBadge: '巷弄收藏家',
    unlockHint: '抵達氹仔後自動解鎖',
    moodTags: ['拍照', '美食', '慢遊'],
    chapters: [
      { id: 1031, title: '序章：彩色外牆', summary: '糖果色外牆是這條故事的開場白。', detail: '走進氹仔，旅程會從色彩與空氣開始變得柔和。', achievement: '解鎖巷弄慢時光', collectible: '彩牆貼紙', locationName: '龍環葡韻', locked: true },
      { id: 1032, title: '第一章：甜點小徑', summary: '一口蛋撻和一條小巷都能成為記憶。', detail: '沿路收集甜點與街景印象，會解鎖新的 UGC 靈感。', achievement: '甜點收藏分頁', collectible: '蛋撻香氣票券', locationName: '氹仔舊城區', locked: true },
      { id: 1033, title: '終章：薄暮散步', summary: '薄暮時分的街巷最適合慢遊。', detail: '完成後可解鎖更適合夜色散步的推薦清單。', achievement: '稱號：慢遊收藏家', collectible: '巷光明信片', locationName: '氹仔海邊馬路', locked: true },
    ],
  },
  {
    id: 4,
    name: '海風與燈塔',
    nameEn: 'Coastal Echoes',
    description: '沿着路环海岸走，海风会把节奏拉慢，也会把城市边界慢慢打开。',
    icon: '🌊',
    coverColor: '#dce8ff',
    totalChapters: 3,
    completedChapters: 0,
    estimatedTime: '2小時',
    difficulty: 'medium',
    poiIds: [5],
    chapterTitles: ['序章：黑沙海岸', '第一章：燈塔守望', '終章：海霧日記'],
    progress: 0,
    rewardBadge: '海風觀察員',
    unlockHint: '抵達路環後自動解鎖',
    moodTags: ['海岸', '放鬆', '自然'],
    chapters: [
      { id: 1041, title: '序章：黑沙海岸', summary: '黑色沙粒会把脚步变慢。', detail: '海风和沙声在这里是最温柔的背景音。', achievement: '解鎖海岸旅程', collectible: '海砂玻璃瓶', locationName: '黑沙海灘', locked: true },
      { id: 1042, title: '第一章：燈塔守望', summary: '往更远一点的地方去看海。', detail: '这段路适合留给愿意慢慢走的人。', achievement: '海岸足跡加成', collectible: '燈塔貼章', locationName: '路環沿岸', locked: true },
      { id: 1043, title: '終章：海霧日記', summary: '把海风装进这趟旅程的最后一页。', detail: '完成後會解鎖適合傍晚散步的推薦。', achievement: '稱號：海風觀察員', collectible: '海霧筆記', locationName: '路環海岸', locked: true },
    ],
  },
]

export const mockStamps: StampItem[] = [
  { id: 101, type: 'location', name: '大三巴足跡章', description: '抵達大三巴牌坊', icon: '🏛️', collected: true, collectedAt: '2026-04-06T10:30:00+08:00', poiId: 1, rarity: 'common' },
  { id: 102, type: 'location', name: '議事亭足跡章', description: '抵達議事亭前地', icon: '🏟️', collected: true, collectedAt: '2026-04-06T11:05:00+08:00', poiId: 2, rarity: 'common' },
  { id: 103, type: 'story', name: '絲路序章章', description: '完成海上絲路序章', icon: '📖', collected: true, collectedAt: '2026-04-06T12:30:00+08:00', storyId: 1, rarity: 'rare' },
  { id: 104, type: 'mission', name: '初探澳門', description: '完成 3 枚足跡章', icon: '🎯', collected: true, collectedAt: '2026-04-06T13:00:00+08:00', rarity: 'common' },
  { id: 105, type: 'secret', name: '玫瑰堂回響', description: '夜色模式下完成一次故事觸發', icon: '🌙', collected: false, poiId: 2, rarity: 'epic' },
  { id: 106, type: 'location', name: '葡韻慢遊章', description: '首次抵達氹仔舊城區', icon: '🏘️', collected: false, poiId: 4, rarity: 'rare' },
  { id: 107, type: 'location', name: '海風觀察章', description: '首次抵達黑沙海灘', icon: '🌊', collected: false, poiId: 5, rarity: 'rare' },
]

export const mockRewards: RewardItem[] = [
  { id: 1, name: '澳門老城明信片', subtitle: '實體兌換', icon: '💌', stampCost: 4, inventory: 128, status: 'available', description: '收集足跡章即可兌換一套主題明信片。', highlight: '適合在旅途終點帶走一份紀念' },
  { id: 2, name: '海上絲路限定徽章', subtitle: '虛擬收藏', icon: '🪙', stampCost: 6, inventory: 999, status: 'available', description: '完成故事線里程碑後可解鎖頭像框與稱號。', highlight: '收集控最愛的限定徽章' },
  { id: 3, name: '葡式蛋撻優惠券', subtitle: '合作商戶', icon: '🧁', stampCost: 8, inventory: 26, status: 'coming_soon', description: '打卡夠多後可解鎖的城市甜點小驚喜。', highlight: '下一站很適合搭配慢遊日程' },
]

export const mockDiscoverCards: DiscoverCardItem[] = [
  { id: 201, title: '福隆新街夜遊活動', subtitle: '活動推薦', description: '夜間限定導覽，沿著老街點亮故事節點與章節彩蛋。', tag: '今晚可參加', icon: '🌃', type: 'activity', district: '澳門半島', actionText: '查看活動', coverColor: '#ffe2ef' },
  { id: 202, title: '葡式蛋撻合作商戶', subtitle: '商戶推薦', description: '打卡後可去合作小店兌換旅途小驚喜。', tag: '徽章兌換', icon: '🧁', type: 'merchant', district: '議事亭周邊', actionText: '去兌換', coverColor: '#fff0c8' },
  { id: 203, title: '本週熱點打卡榜', subtitle: '熱門足跡', description: '大三巴、媽閣廟與議事亭依旧是旅人最爱的三大任務點。', tag: '熱度上升', icon: '🔥', type: 'checkin', district: '歷史城區', actionText: '跟著打卡', coverColor: '#dff3ff' },
]

export const mockTipArticles: TipArticleItem[] = [
  {
    id: 301,
    title: '第一次來澳門怎麼玩最順？',
    summary: '用 2 條故事線串起歷史城區，不走回頭路也能快速收章。',
    coverColor: '#ffe4ef',
    category: '新手攻略',
    author: '澳小遊編輯部',
    likes: 128,
    saves: 94,
    readMinutes: 5,
    tags: ['路線', '新手', '打卡'],
    locationName: '澳門半島',
    contentParagraphs: ['先從大三巴一帶開始，城市節奏會很快進入狀態。', '再往議事亭前地慢慢走，就能把故事和打卡章串起來。'],
  },
  {
    id: 302,
    title: '長者友好的半日慢遊路線',
    summary: '集中在媽閣與議事亭周邊，節奏慢、步行短，適合語音導覽模式。',
    coverColor: '#e8f7ff',
    category: '慢遊推薦',
    author: '城市導覽官',
    likes: 86,
    saves: 73,
    readMinutes: 4,
    tags: ['長者模式', '慢遊', '語音'],
    locationName: '媽閣廟',
    contentParagraphs: ['如果想把旅程走得慢一点，可以先挑能坐下休息的节点。', '语音导览和大字显示会让整段路更轻松。'],
  },
  {
    id: 303,
    title: '澳門拍照最出片的 5 個點',
    summary: '從大三巴正面到玫瑰堂側街，附最佳光線時間與取景提醒。',
    coverColor: '#fff3cf',
    category: '拍照秘籍',
    author: '旅拍愛好者',
    likes: 211,
    saves: 157,
    readMinutes: 6,
    tags: ['拍照', '攻略', '熱門'],
    locationName: '大三巴牌坊',
    contentParagraphs: ['柔和光线最适合在清晨和傍晚拍摄粉彩建筑。', '记得往侧街多走几步，往往能找到更安静的构图角度。'],
  },
]

export const mockNotifications: NotificationItem[] = [
  { id: 1, title: '你的旅途提醒已送达', content: '今晚福隆新街夜遊活動還有空位，記得提早出發。', timeLabel: '10 分鐘前', unread: true, type: 'activity' },
  { id: 2, title: '有人收藏了你的秘籍草稿', content: '旅拍愛好者很喜歡你剛剛整理的拍照靈感。', timeLabel: '1 小時前', unread: true, type: 'ugc' },
  { id: 3, title: '新城市等待解鎖', content: '當你靠近氹仔或路環時，會自動點亮新的城市旅程。', timeLabel: '今天', unread: false, type: 'system' },
]

export const mockTravelRecommendations: TravelRecommendation[] = [
  {
    storyId: 1,
    storyName: '海上絲路',
    activityTitle: '媽閣慢遊導覽',
    poiName: '媽閣廟',
    ugcTitle: '長者友好的半日慢遊路線',
    reason: '更適合偏好文化、節奏輕鬆與 2 小時內完成的旅人。',
  },
  {
    storyId: 2,
    storyName: '東西方戰事',
    activityTitle: '大三巴歷史線索尋章',
    poiName: '大三巴牌坊',
    ugcTitle: '第一次來澳門怎麼玩最順？',
    reason: '適合第一次來澳門、喜歡城市地標與高人氣路線的旅人。',
  },
  {
    storyId: 3,
    storyName: '巷弄慢時光',
    activityTitle: '氹仔甜點與小巷拍照散步',
    poiName: '龍環葡韻',
    ugcTitle: '澳門拍照最出片的 5 個點',
    reason: '更適合喜歡拍照、美食與慢遊節奏的旅人。',
  },
]

export const mockArrivalExperiences: Record<number, ArrivalExperience> = {
  1: { poiId: 1, title: '你已抵達大三巴牌坊', narrative: '火炮與鐘聲在城牆外回響，東西方故事線在這裡正式交會。', audioTitle: '大三巴導覽音頻', audioDuration: '01:28', rewardLabel: '解鎖足跡章 + 東西方戰事主線', canManualCheckin: true },
  2: { poiId: 2, title: '你已抵達議事亭前地', narrative: '廣場作為城市節點，最適合串接後續獎勵與商戶探索。', audioTitle: '議事亭城市播報', audioDuration: '01:10', rewardLabel: '解鎖城市廣場章', canManualCheckin: true },
  3: { poiId: 3, title: '你已抵達媽閣廟', narrative: '海上絲路的序章在這裡開啟，信仰與航海記憶一同甦醒。', audioTitle: '媽閣廟海風導覽', audioDuration: '01:42', rewardLabel: '解鎖絲路序章章', canManualCheckin: false },
  4: { poiId: 4, title: '你已抵達龍環葡韻', narrative: '薄荷色小屋和微風一起，把這座小城的慢節奏交到你手上。', audioTitle: '葡韻慢遊導覽', audioDuration: '01:16', rewardLabel: '解鎖葡韻慢遊章', canManualCheckin: true },
  5: { poiId: 5, title: '你已抵達黑沙海灘', narrative: '黑色細沙與海浪會把旅程拉慢，也會把新的城市解鎖。', audioTitle: '黑沙海岸導覽', audioDuration: '01:34', rewardLabel: '解鎖海風觀察章', canManualCheckin: true },
}

export const mockCheckinResults: Record<number, CheckinResult> = {
  1: { success: true, poiId: 1, poiName: '大三巴牌坊', stampId: 101, stampName: '大三巴足跡章', experienceGained: 30, triggerMode: 'gps', unlockedStorylineId: 2 },
  2: { success: true, poiId: 2, poiName: '議事亭前地', stampId: 102, stampName: '議事亭足跡章', experienceGained: 20, triggerMode: 'gps' },
  3: { success: true, poiId: 3, poiName: '媽閣廟', stampId: 103, stampName: '絲路序章章', experienceGained: 40, triggerMode: 'gps', unlockedStorylineId: 1 },
  4: { success: true, poiId: 4, poiName: '龍環葡韻', stampId: 106, stampName: '葡韻慢遊章', experienceGained: 28, triggerMode: 'gps', unlockedStorylineId: 3 },
  5: { success: true, poiId: 5, poiName: '黑沙海灘', stampId: 107, stampName: '海風觀察章', experienceGained: 32, triggerMode: 'gps', unlockedStorylineId: 4 },
}
